(function(){
'use strict';
const DAYS=(window.TRIP_DATA&&window.TRIP_DATA.DAYS)||[];
const ZONES=(window.EXPLORE_DATA&&window.EXPLORE_DATA.ZONES)||{};
const $=s=>document.querySelector(s),$$=s=>Array.prototype.slice.call(document.querySelectorAll(s));
let dayIndex=0,manualStop=-1,map=null,mapReady=false,planMarkers=[],bonusMarkers=[],poly=null;let done=new Set();
try{done=new Set(JSON.parse(localStorage.getItem('jmax.done')||'[]'))}catch(e){}
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const valid=s=>s&&Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lng));
function pinLink(s){if(valid(s))return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(Number(s.lat).toFixed(6)+','+Number(s.lng).toFixed(6));return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((s&&s.q)||(s&&s.name)||'Japan')}
function searchLink(q,context){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q+(context?' '+context:''))}
function routeLink(d){if(!d||!d.stops)return 'https://www.google.com/maps';const pts=d.stops.filter(valid);if(pts.length<2)return pts[0]?pinLink(pts[0]):'https://www.google.com/maps';const keep=[pts[0]].concat(pts.slice(1,-1).filter(x=>x.priority==='MUST'||x.priority==='BOOK'||x.priority==='HIGH').slice(0,8),[pts[pts.length-1]]);let u='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(keep[0].lat+','+keep[0].lng)+'&destination='+encodeURIComponent(keep[keep.length-1].lat+','+keep[keep.length-1].lng);if(keep.length>2)u+='&waypoints='+encodeURIComponent(keep.slice(1,-1).map(x=>x.lat+','+x.lng).join('|'));return u}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1700)}
function dateKey(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return ''}}
function jstMinutes(){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return Number(p.find(x=>x.type==='hour').value)*60+Number(p.find(x=>x.type==='minute').value)}catch(e){return 0}}
function minOf(t){if(!/^\d{2}:\d{2}$/.test(t||''))return null;const a=t.split(':').map(Number);return a[0]*60+a[1]}
function autoDay(){const i=DAYS.findIndex(d=>d.date===dateKey());return i>=0?i:0}
function autoStop(){const d=DAYS[dayIndex];if(!d||d.date!==dateKey())return-1;const now=jstMinutes();let idx=0;d.stops.forEach((s,i)=>{const m=minOf(s.time);if(m!==null&&now>=m)idx=i});return idx}
function activeStop(){return manualStop>=0?manualStop:autoStop()}
function itemKey(i){return DAYS[dayIndex].date+':'+i}
function zones(){return ZONES[DAYS[dayIndex].date]||[]}
function zoneRange(z){const m=(z.time||'').match(/(\d{2}:\d{2})\s*[–-]\s*(\d{2}:\d{2}|late)/);return m?[minOf(m[1]),m[2]==='late'?24*60:minOf(m[2])]:null}
function zoneForStop(s){const m=minOf(s.time),zs=zones();if(m!==null){for(let i=0;i<zs.length;i++){const r=zoneRange(zs[i]);if(r&&m>=r[0]&&m<=r[1])return zs[i]}}return zs[0]||null}
function stopImage(s){const z=zoneForStop(s);return (s&&s.img)||(z&&z.img)||DAYS[dayIndex].img||''}
function renderDayRail(){const r=$('#dayRail');if(!r)return;r.innerHTML='';DAYS.forEach((d,i)=>{const b=document.createElement('button');b.className='day-pill'+(i===dayIndex?' active':'');b.textContent=d.short+' · '+d.city.split(' · ')[0];b.onclick=()=>setDay(i);r.appendChild(b)});setTimeout(()=>{const a=r.querySelector('.active');if(a&&a.scrollIntoView)try{a.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}catch(e){}},40)}
function setDay(i){if(!DAYS[i])return;dayIndex=i;manualStop=-1;try{localStorage.setItem('jmax.day',String(i))}catch(e){}renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function renderHero(){const d=DAYS[dayIndex],z=zones()[0];const img=(z&&z.img)||d.img;const hp=$('.hero-photo');if(hp)hp.style.backgroundImage='url("'+img+'")';$('#heroLabel').textContent='DAY '+String(dayIndex+1).padStart(2,'0')+' · '+d.short;$('#heroTitle').textContent=d.title;$('#heroMission').textContent=d.mission;$('#heroCity').textContent=d.city;$('#heroSleep').textContent='SLEEP · '+d.sleep;$('#dayRoute').href=routeLink(d);$('#mapFallbackRoute').href=routeLink(d)}
function renderZoneStrip(){const box=$('#zoneStrip'),zs=zones();if(!box)return;box.innerHTML=zs.map((z,i)=>'<article class="zone-mini" data-zone="'+i+'"><div class="zone-mini-img" style="background-image:url(\''+esc(z.img)+'\')"></div><div class="zone-mini-copy"><span>'+esc(z.time)+'</span><h3>'+esc(z.name)+'</h3><p>'+esc(z.summary)+'</p><div class="zone-mini-meta">'+(z.extras||[]).length+' bonus pins · '+(z.food||[]).length+' food ideas</div></div><button class="zone-open" data-zone="'+i+'">Explore</button></article>').join('');$$('.zone-open').forEach(b=>b.onclick=e=>{e.stopPropagation();switchPanel('explore');setTimeout(()=>document.querySelector('#zone-'+b.dataset.zone)?.scrollIntoView({behavior:'smooth',block:'start'}),80)});$$('.zone-mini').forEach(c=>c.onclick=()=>{switchPanel('explore');setTimeout(()=>document.querySelector('#zone-'+c.dataset.zone)?.scrollIntoView({behavior:'smooth',block:'start'}),80)})}
function renderTimeline(){const d=DAYS[dayIndex],r=$('#timeline');if(!r)return;r.innerHTML='';d.stops.forEach((s,i)=>{const a=document.createElement('article');a.className='stop'+(i===activeStop()?' current':'')+(done.has(itemKey(i))?' done':'');a.innerHTML='<div class="stop-time">'+esc(s.time)+'<small>'+esc(s.end||'')+'</small></div><div class="thumb" style="background-image:url(\''+esc(stopImage(s))+'\')"></div><div class="stop-copy"><div class="stop-title-row"><h3>'+esc(s.name)+'</h3><span class="priority '+String(s.priority).toLowerCase()+'">'+esc(s.priority)+'</span></div><p>'+esc(s.desc)+'</p><div class="stop-tools"><a class="pin-btn" href="'+pinLink(s)+'" target="_blank" rel="noopener">Exact Google pin ↗</a><button class="detail">Details</button></div></div><button class="check '+(done.has(itemKey(i))?'checked':'')+'">✓</button>';a.querySelector('.detail').onclick=()=>openDrawer(s,'scheduled');a.querySelector('.check').onclick=()=>{const k=itemKey(i);done.has(k)?done.delete(k):done.add(k);try{localStorage.setItem('jmax.done',JSON.stringify(Array.from(done)))}catch(e){}renderTimeline()};a.onclick=e=>{if(e.target.closest('a,button'))return;manualStop=i;renderTimeline();live();if(mapReady)focusPlan(i)};r.appendChild(a)})}
function renderExplore(){const box=$('#zoneGuide'),zs=zones();if(!box)return;box.innerHTML=zs.map((z,zi)=>{const extras=(z.extras||[]).map((x,xi)=>'<div class="explore-row"><div class="explore-icon">'+(x.type==='photo'?'◉':x.type==='detour'?'↗':'＋')+'</div><div><h4>'+esc(x.name)+'</h4><p>'+esc(x.note)+'</p><a href="'+pinLink(x)+'" target="_blank" rel="noopener">Exact pin ↗</a></div></div>').join('');const foods=(z.food||[]).map(f=>'<div class="food-row"><div><h4>'+esc(f.name)+'</h4><p>'+esc(f.note)+'</p></div><a href="'+searchLink(f.q||f.name,DAYS[dayIndex].city)+'" target="_blank" rel="noopener">Maps ↗</a></div>').join('');return '<article class="zone-card" id="zone-'+zi+'"><div class="zone-image" style="background-image:url(\''+esc(z.img)+'\')"><div><span>'+esc(z.time)+'</span><h3>'+esc(z.name)+'</h3></div></div><div class="zone-body"><p class="zone-summary">'+esc(z.summary)+'</p><div class="zone-actions"><button class="show-zone-map" data-zone="'+zi+'">Show these pins on map</button></div>'+(extras?'<div class="zone-section"><div class="section-label">WORTH ADDING IF YOU ARE HERE</div>'+extras+'</div>':'')+(foods?'<div class="zone-section"><div class="section-label">FOOD / BREAK OPTIONS</div>'+foods+'</div>':'')+'</div></article>'}).join('');$$('.show-zone-map').forEach(b=>b.onclick=()=>{switchPanel('map');setTimeout(()=>focusZone(Number(b.dataset.zone)),120)})}
function renderTripGrid(){const g=$('#tripGrid');if(!g)return;g.innerHTML=DAYS.map((d,i)=>{const z=(ZONES[d.date]||[])[0];return '<article class="trip-card" data-day="'+i+'" style="background-image:url(\''+esc((z&&z.img)||d.img)+'\')"><div><span>'+esc(d.short)+' · DAY '+(i+1)+'</span><h3>'+esc(d.city)+'</h3><p>'+esc(d.title)+'</p></div></article>'}).join('');$$('.trip-card').forEach(c=>c.onclick=()=>{setDay(Number(c.dataset.day));switchPanel('timeline')})}
function live(){const d=DAYS[dayIndex];if(!d||!d.stops.length)return;const i=activeStop(),base=i>=0?i:0,now=d.stops[base],next=d.stops[Math.min(base+1,d.stops.length-1)];$('#liveStatus').textContent=(d.date===dateKey()?'LIVE · ':'PLANNING · ')+d.short;$('#nowName').textContent=now.name;$('#nowDesc').textContent=now.desc;$('#nextName').textContent=next.name;$('#nextGo').href=pinLink(next);$('#progressBar').style.width=((base+1)/d.stops.length*100)+'%'}
function ensureMap(){if(mapReady)return true;if(!window.L){$('#mapFallback').hidden=false;$('#map').style.display='none';return false}try{map=L.map('map',{zoomControl:false,preferCanvas:true});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);mapReady=true;return true}catch(e){$('#mapFallback').hidden=false;$('#map').style.display='none';return false}}
function planIcon(i,p){const c=(p==='MUST'||p==='BOOK')?'#0A84FF':p==='HIGH'?'#3B82F6':'#7A8A9A';return L.divIcon({className:'',html:'<div class="plan-pin" style="background:'+c+'">'+(i+1)+'</div>',iconSize:[30,30],iconAnchor:[15,15]})}
function bonusIcon(type){return L.divIcon({className:'',html:'<div class="bonus-pin '+esc(type||'bonus')+'">'+(type==='photo'?'◉':type==='detour'?'↗':'＋')+'</div>',iconSize:[26,26],iconAnchor:[13,13]})}
function renderMap(){if(!ensureMap())return;planMarkers.concat(bonusMarkers).forEach(m=>{try{m.remove()}catch(e){}});planMarkers=[];bonusMarkers=[];if(poly){try{poly.remove()}catch(e){}poly=null}const d=DAYS[dayIndex],ll=[],route=[];d.stops.forEach((s,i)=>{if(!valid(s))return;const xy=[Number(s.lat),Number(s.lng)];ll.push(xy);route.push(xy);const m=L.marker(xy,{icon:planIcon(i,s.priority)}).addTo(map).bindPopup('<div class="map-pop"><b>'+esc(s.time)+' · '+esc(s.name)+'</b><p>'+esc(s.desc)+'</p><a target="_blank" rel="noopener" href="'+pinLink(s)+'">Exact Google pin ↗</a></div>');m.on('click',()=>{manualStop=i;renderTimeline();live()});planMarkers[i]=m});zones().forEach((z,zi)=>(z.extras||[]).forEach(x=>{if(!valid(x))return;const xy=[Number(x.lat),Number(x.lng)];ll.push(xy);const m=L.marker(xy,{icon:bonusIcon(x.type)}).addTo(map).bindPopup('<div class="map-pop bonus"><b>'+esc(x.name)+'</b><small>'+esc(z.name)+'</small><p>'+esc(x.note)+'</p><a target="_blank" rel="noopener" href="'+pinLink(x)+'">Exact Google pin ↗</a></div>');bonusMarkers.push(m)}));if(route.length>1)poly=L.polyline(route,{color:'#0A84FF',weight:4,opacity:.78}).addTo(map);if(ll.length)map.fitBounds(ll,{padding:[30,30],maxZoom:14});setTimeout(()=>map.invalidateSize(),80)}
function focusPlan(i){const m=planMarkers[i];if(map&&m){map.setView(m.getLatLng(),16);m.openPopup()}}
function focusZone(zi){if(!ensureMap())return;renderMap();const z=zones()[zi],pts=(z&&z.extras||[]).filter(valid).map(x=>[Number(x.lat),Number(x.lng)]);if(pts.length)map.fitBounds(pts,{padding:[48,48],maxZoom:16})}
function openDrawer(x,kind){$('#drawerImg').style.backgroundImage='url("'+(kind==='scheduled'?stopImage(x):((zoneForStop(x)||{}).img||DAYS[dayIndex].img))+'")';$('#drawerType').textContent=(kind==='scheduled'?(x.priority+' · '+x.type):'BONUS PIN');$('#drawerName').textContent=x.name;$('#drawerDesc').textContent=x.desc||x.note||'';$('#drawerFood').innerHTML=kind==='scheduled'&&x.food?'<b>FOOD NOTE</b><p>'+esc(x.food)+'</p>':'';$('#drawerButtons').innerHTML='<a href="'+pinLink(x)+'" target="_blank" rel="noopener">Open exact Google pin ↗</a>';$('#drawer').classList.add('open');$('#drawerBackdrop').classList.add('open')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawerBackdrop').classList.remove('open')}
function switchPanel(p){$$('.tab,.mobile-tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===p));$$('.panel').forEach(x=>x.classList.remove('active'));const el=$('#'+p+'Panel');if(el)el.classList.add('active');if(p==='map')setTimeout(renderMap,60);if(p==='explore')renderExplore();window.scrollTo({top:document.querySelector('.section-tabs').offsetTop-90,behavior:'smooth'})}
function searchData(q){const out=[];DAYS.forEach((d,di)=>d.stops.forEach((s,si)=>{if((d.city+' '+s.name+' '+s.type+' '+s.desc+' '+(s.food||'')).toLowerCase().includes(q))out.push({kind:'stop',d,di,s,si})}));Object.keys(ZONES).forEach(date=>(ZONES[date]||[]).forEach(z=>{const di=DAYS.findIndex(d=>d.date===date);(z.extras||[]).forEach(x=>{if((z.name+' '+x.name+' '+x.note).toLowerCase().includes(q))out.push({kind:'extra',di,x,z})});(z.food||[]).forEach(f=>{if((z.name+' '+f.name+' '+f.note).toLowerCase().includes(q))out.push({kind:'food',di,f,z})})}));return out}
function bind(){$$('.tab,.mobile-tab').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));$('#homeBtn').onclick=()=>{setDay(autoDay());switchPanel('timeline')};$('#fitMap').onclick=renderMap;$('#resetDay').onclick=()=>{manualStop=-1;renderTimeline();live();toast('Following schedule')};$('#jumpCurrent').onclick=()=>{manualStop=-1;const ad=autoDay();if(ad!==dayIndex)setDay(ad);else{renderTimeline();live()}toast('Following Japan time')};$('#locate').onclick=()=>{if(!navigator.geolocation)return toast('Location unavailable');navigator.geolocation.getCurrentPosition(p=>{let best={d:Infinity,i:0};DAYS[dayIndex].stops.forEach((s,i)=>{if(!valid(s))return;const dx=(p.coords.latitude-s.lat)*111,dy=(p.coords.longitude-s.lng)*90,dist=Math.sqrt(dx*dx+dy*dy);if(dist<best.d)best={d:dist,i}});manualStop=best.i;renderTimeline();live();switchPanel('map');setTimeout(()=>focusPlan(best.i),120);toast('Closest planned stop: '+DAYS[dayIndex].stops[best.i].name)},()=>toast('Allow location access on your phone'),{enableHighAccuracy:true,timeout:9000,maximumAge:60000})};$('#shareStatus').onclick=async()=>{const d=DAYS[dayIndex],i=Math.max(activeStop(),0),s=d.stops[i],n=d.stops[Math.min(i+1,d.stops.length-1)],text='Japan Max — We are at '+s.name+'. Next: '+n.name+' '+pinLink(n);try{if(navigator.share)await navigator.share({title:'Japan Max',text});else{await navigator.clipboard.writeText(text);toast('Copied')}}catch(e){}};$('#closeDrawer').onclick=closeDrawer;$('#drawerBackdrop').onclick=closeDrawer;$('#searchBtn').onclick=()=>{$('#searchOverlay').classList.add('open');setTimeout(()=>$('#searchInput').focus(),30)};$('#closeSearch').onclick=()=>$('#searchOverlay').classList.remove('open');$('#searchInput').oninput=e=>{const q=e.target.value.trim().toLowerCase(),out=q?searchData(q):[];$('#searchResults').innerHTML=out.slice(0,60).map((x,i)=>'<div class="search-result" data-r="'+i+'"><b>'+esc(x.kind==='stop'?x.s.name:x.kind==='extra'?x.x.name:x.f.name)+'</b><small>'+esc(DAYS[x.di]?.short||'')+' · '+esc(x.kind==='extra'?x.z.name:x.kind==='food'?x.z.name:DAYS[x.di].city)+'</small></div>').join('');$$('.search-result').forEach((el,i)=>el.onclick=()=>{const x=out[i];$('#searchOverlay').classList.remove('open');setDay(x.di);if(x.kind==='stop'){manualStop=x.si;renderTimeline();live();openDrawer(x.s,'scheduled')}else if(x.kind==='extra'){switchPanel('explore');setTimeout(()=>document.getElementById('zone-'+(ZONES[DAYS[x.di].date]||[]).indexOf(x.z))?.scrollIntoView({behavior:'smooth'}),80)}else{switchPanel('explore')}})}}
function renderAll(){renderDayRail();renderHero();renderZoneStrip();renderTimeline();renderExplore();renderTripGrid();live();if(mapReady)renderMap()}
function tick(){try{$('#clock').textContent='JST '+new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date());if(manualStop<0)live()}catch(e){}}
function init(){if(!DAYS.length){document.body.innerHTML='<main style="padding:40px;font-family:-apple-system,sans-serif"><h1>Trip data did not load.</h1><p>Refresh once.</p></main>';return}let saved=Number(localStorage.getItem('jmax.day'));dayIndex=Number.isFinite(saved)&&saved>=0&&saved<DAYS.length?saved:autoDay();bind();renderAll();tick();setInterval(tick,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();