const XIMG={
 glover:'https://www.nagasaki-tabinet.com/storage/tourism_attractions/101/responsive_images/1IH1c0CWx6n3XaeT41S9QxvbWs10QrKdi9TS4L1s__1382_1037.jpeg',
 dejima:'https://cdn.4travel.jp/img/thumbnails/imk/travelogue_pict/86/89/88/650x_86898842.jpg?updated_at=1753434850',
 takachiho:'https://megapx-assets.dcard.tw/images/ca1d3328-511a-4838-9429-184b3d8744ac/1280.jpeg',
 himeji:'https://imgcp.aacdn.jp/img-a/1200/900/aa_news/article/2025/12/08/6936935a95e9e.jpg',
 kobe:'https://live.staticflickr.com/7380/12644851733_4c52c80c6b_b.jpg',
 arashiyama:'https://mediaim.expedia.com/destination/2/6f024abcd72a361f2ef55a471e0d51a6.jpg',
 kinkaku:'https://www.petitfute.com/medias/mag/40726/originale/AdobeStock_551595403_Editorial_Use_Only-1024x683.jpeg',
 nanzen:'https://article.his-j.com/assets/kokunai/2025/01/kyoto_nanzenji_62537d11-ab9c-4c45-9e1b-6241d2867b3b.jpg',
 nishiki:'https://i0.wp.com/jetsettingfools.com/wp-content/uploads/2018/11/Nishiki-Market-Kyoto-Japan.jpg?ssl=1&w=683',
 gion:'https://tourjapan.ru/upload/webp/iblock/290/290be4f77fa0e57ddeb825e4df985ab9.jpg.webp',
 fushimi:'https://deih43ym53wif.cloudfront.net/fushimi-inari-shrine-kyoto_734a8775a3.jpeg',
 shinjuku:'https://svcstrg.cld.navitime.jp/travelguide/p13150008/p13150008_06t.jpg',
 shibuya:'https://images.microcms-assets.io/assets/14d13bd618dc45c7b684223c0ca9d033/8707cf894ffd46f2b1e680e020af3ef7/timo-volz-DGsqL2j028E-unsplash.jpg',
 odaiba:'https://www.gotokyo.org/shared/images/pages/destinations/southern-tokyo/odaiba/images/40_0121_3.jpg',
 nikko:'https://res-4.cloudinary.com/jnto/image/upload/w_1000%2Ch_667%2Cc_fill%2Cf_auto%2Cfl_lossy%2Cq_auto/v1/media/filer_public/a2/1e/a21e7fc7-1c59-4a31-bb66-2120383c6c53/pixta_44438082_m_oyhopx',
 kamakura:'https://res.klook.com/image/upload/activities/wgzm5fhrd46mvjha3d8j.jpg',
 meiji:'https://www.charterbus-limousine.com/common/img/privatetour/oneday_tour_photo01.webp',
 sensoji:'https://cdn.tourradar.com/s3/tour/750x400/124673_1160fbed.jpg',
 akihabara:'https://images.squarespace-cdn.com/content/v1/5d31e18d1abe780001b2653d/34cca6ca-07aa-4676-bb96-32c7815cceca/2023%2BJapan-9273.jpg?format=2500w',
 dotonbori:'https://images.microcms-assets.io/assets/14d13bd618dc45c7b684223c0ca9d033/111de767b2f24792afd66dd541b3c520/pixta_98794822_M.jpg'
};
const xp=(name,lat,lng,type,note,q=name)=>({name,lat,lng,type,note,q});
const food=(name,note,q=name)=>({name,note,q});
const ZONES={
'2026-09-22':[
 {name:'Station → Urakami',time:'10:18–13:20',mode:'transit',img:XIMG.dejima,summary:'Start with Christian history, then move north into the atomic-bomb memorial district. Do not bounce back toward downtown until this block is finished.',extras:[xp('Nagasaki Museum of History and Culture',32.7539,129.8790,'bonus','Strong rainy-day/history add near the center, but not worth breaking the northbound flow unless weather forces a swap.'),xp('Suwa Shrine',32.7578,129.8816,'bonus','Beautiful staircase shrine above central Nagasaki. Save only if the group is ahead; the Ryoma hillside later gives you a stronger shrine/view combo.')],food:[food('Yossou Hamamachi','Classic Nagasaki chawanmushi; better later when you pass Hamamachi than as a morning detour.'),food('CHAMPON 358','Fast central champon option if Chinatown timing collapses.')]},
 {name:'Ryoma hillside → Temple Row',time:'13:35–15:20',mode:'walking',img:XIMG.glover,summary:'Taxi to the top at Kazagashira, then work downhill. This is the key trick: never climb the whole Ryoma/Wakamiya section from downtown.',extras:[xp('Kameyama Shachu Memorial Museum',32.7500,129.8871,'bonus','Small Ryoma-history stop right on the descent. Add only if there is no line and you want more history.'),xp('Shofukuji Temple',32.7520,129.8792,'bonus','Quiet temple close to your route; first temple to skip if you already feel temple saturation.'),xp('Nakashimagawa Park',32.7480,129.8775,'bonus','Use the river level for the stone-bridge reflections and a breather before continuing south.')],food:[food('Yossou Hamamachi','Historic chawanmushi + steamed sushi near Hamamachi.'),food('Tsuruchan','Old-school Nagasaki “Turkish rice” option near the arcade if you want a local dish instead of champon.')]},
 {name:'Chinatown → Dejima → South Historic District',time:'15:20–18:30',mode:'walking',img:XIMG.glover,summary:'This is one continuous southbound walk: Chinatown, Dejima, harbor, Dutch Slope, Oura and Glover. The route only works if you stop treating each attraction like a separate trip.',extras:[xp('Nagasaki Confucius Shrine',32.7348,129.8731,'bonus','Colorful Chinese cultural site between Dutch Slope and Oura; worth a quick exterior if you are on time.'),xp('Higashiyamate 12 Bankan',32.7366,129.8740,'bonus','Western-style building inside the Dutch Slope area; only enter if it is immediately open.'),xp('Oura Cathedral',32.7346,129.8701,'bonus','The exterior and forecourt already add context; interior is optional on this max-route day.')],food:[food('Shikairou','The historic champon/sara-udon institution right by Oura. Great if timing matches and the line is sane; no reservation for normal restaurant seating.'),food('Attic Coffee Dejima Wharf','Waterfront coffee, castella and a fast sit-down option directly at Dejima Wharf.')]},
 {name:'Sunset → Mt. Inasa → Shianbashi',time:'18:06–late',mode:'driving',img:XIMG.glover,summary:'Two viewpoints, two different scales: Nabekanmuriyama gives the harbor close-up at sunset; Inasa gives the whole city after dark.',extras:[xp('Inasayama Park',32.7522,129.8492,'bonus','Same mountain experience as the observatory — do not count it as a separate stop.'),xp('Maruyama Park Nagasaki',32.7410,129.8800,'bonus','Small historic nightlife-area park by Shianbashi; wander only if dinner/bar flow takes you there naturally.')],food:[food('Shianbashi Yokocho area','Pick a lively izakaya with seats now rather than chasing a famous queue.'),food('Kaniya Honten','Local late-night rice-ball/ochazuke institution around Shianbashi; useful after drinks.')]}
],
'2026-09-23':[
 {name:'Itoshima decision branch',time:'morning',mode:'driving',img:XIMG.takachiho,summary:'Only run this if the early rental pickup is genuinely available. Futamigaura is the protected coastal stop; Keya and Shiraito are cuttable.',extras:[xp('Palm Tree Swing',33.6099,130.1147,'bonus','Fun coastal photo add if the road is empty, but lower value than Futamigaura.'),xp('Keya Beach',33.5947,130.1055,'bonus','Quick sea look if Keya no Oto timing is clean.')],food:[food('CURRENT cafe / Itoshima coast cafes','Only stop if there is zero wait; do not sacrifice friend pickup or Yufuin daylight for a café.')]},
 {name:'Yufuin core',time:'16:30–18:20',mode:'walking',img:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1400&q=80',summary:'Park once. Do the lake and shrine first, then walk back through Yunotsubo as light fades. Shopping is the expendable part.',extras:[xp('Bussanji Temple',33.2631,131.3695,'bonus','Quiet thatched-roof temple immediately south of Lake Kinrin; excellent if you want one calm non-shopping stop.'),xp('Yufuin Floral Village',33.2667,131.3670,'bonus','Whimsical English-village/Ghibli-like photo stop. Fun, but not official Studio Ghibli and not more important than the lake.'),xp('Sagiridai Overlook',33.2679,131.4052,'bonus','Panorama over the Yufuin basin. Add only if you still have daylight and the road transfer to Beppu is comfortable.')],food:[food('Cafe La Ruche','Lakeside café by Kinrin; only worthwhile if there is immediate seating.'),food('Yufumabushi Shin','Popular Yufuin rice-and-meat specialty; better as a planned meal than a spontaneous long queue.'),food('B-speak','Roll cake / dessert pickup if still open.'),food('Milch Yufuin','Fast cheesecake/pudding style snack on the walking street.')]},
 {name:'Beppu / Kannawa at night',time:'19:15–late',mode:'walking',img:'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1400&q=80',summary:'Beppu earns its place through steam, onsen and food after dark — not by trying to collect all seven Hells.',extras:[xp('Yukemuri Observatory',33.3216,131.4834,'bonus','High view over Kannawa steam. Better in daylight/blue hour; skip if arriving fully dark.'),xp('Hyotan Onsen',33.3177,131.4798,'bonus','Strong public onsen option in Kannawa if your lodging bath is not enough.')],food:[food('Jigoku Mushi Kobo Kannawa','Steam-cook vegetables, seafood and meat using geothermal vents — the most on-theme dinner.'),food('Toyotsune','Famous toriten option in Beppu proper; good food, but only if it does not force a pointless city detour.')]}
],
'2026-09-24':[
 {name:'Yamanami Highway / Kuju',time:'07:05–10:45',mode:'driving',img:'https://images.unsplash.com/photo-1526481280695-3c687fd643ed?auto=format&fit=crop&w=1400&q=80',summary:'Treat the road itself as an attraction. Short, disciplined pullouts beat one long hike.',extras:[xp('Yamanami Highway Viewpoint',33.1204,131.2370,'photo','Use signed pullouts only; do not stop on blind shoulders.'),xp('Kuju Mountains trailhead',33.0943,131.2208,'bonus','You are not hiking today. The first Makinoto viewpoint is enough.')],food:[food('Chojabaru visitor-center snacks','Restroom + quick food only.'),food('Senomoto Rest House','Soft serve / coffee if there is no line.')]},
 {name:'Kurokawa Onsen',time:'11:00–12:00',mode:'walking',img:'https://images.unsplash.com/photo-1578469645742-46cae010e5d4?auto=format&fit=crop&w=1400&q=80',summary:'Park once and walk the lower river lanes. The atmosphere is cedar, stone, bridges and ryokan — not a checklist of baths.',extras:[xp('Marurin Bridge',33.0864,131.1521,'photo','One of the classic river-level photo points through the ryokan valley.'),xp('Kurokawa Jizoson',33.0867,131.1520,'bonus','Tiny local spiritual stop right inside the village core.')],food:[food('Patisserie Roku','Famous cream-puff/sweets stop; perfect because it does not become a long meal.'),food('Dorayaki / onsen-manju shops','Buy the fastest local sweet you see rather than waiting.')]},
 {name:'Aso caldera',time:'12:35–15:25',mode:'driving',img:'https://www.gettyimages.com/',summary:'Daikanbo gives the full caldera scale; Milk Road gives the drive; Kusasenri puts you inside the landscape. Crater access is not required for this day to work.',extras:[xp('Aso Volcano Museum',32.8919,131.0430,'bonus','Useful weather/volcano context right at Kusasenri. Good rain fallback; not mandatory in clear weather.'),xp('Kusasenri Coffee Roastery',32.8920,131.0422,'food','Easy coffee stop inside the same complex if the group needs caffeine.'),xp('Aso Shrine',32.9482,131.1176,'detour','Historic shrine north/east of the main line. Only add if you deliberately trade away time elsewhere.')],food:[food('Kusasenri / Aso area akaushi','Akaushi beef bowl or steak. Eat quickly; the drive south is long.'),food('Kusasenri Coffee Roastery','Fast coffee without leaving the route.')]},
 {name:'Takachiho night',time:'18:00–late',mode:'driving',img:XIMG.takachiho,summary:'Arrive, park, eat and sleep. Your competitive advantage is waking up beside the gorge.',extras:[xp('Takachiho Shrine',32.7105,131.3078,'bonus','Atmospheric cedar shrine in town. Add only if you arrive early enough that it does not damage sleep.'),xp('Takachiho Kagura Hall',32.7106,131.3078,'bonus','Night Kagura can be memorable, but tomorrow’s gorge/boat is the priority.')],food:[food('Takachiho Beef Restaurant Nagomi','Good target for local Takachiho beef if hours and wait cooperate.'),food('Local chicken nanban / izakaya','Use whatever is open near lodging rather than driving around town.')]}
],
'2026-09-25':[
 {name:'Takachiho Gorge + mythology',time:'06:30–10:05',mode:'driving',img:XIMG.takachiho,summary:'Walk the rim before crowds, make the boat reservation the fixed gate, then decide whether Amano-Iwato is worth the time.',extras:[xp('Manai Falls Overlook',32.7007,131.3016,'photo','Get the falls from above before the boat.'),xp('Three Bridges Viewpoint',32.7018,131.3002,'photo','Classic stacked-bridges composition in the gorge.'),xp('Takachiho Shrine',32.7105,131.3078,'bonus','Add only if Amano-Iwato is cut and you still want one town shrine.')],food:[food('Quick gorge breakfast / konbini','Do not sit down for breakfast before the boat.'),food('Takachiho Beef Nagomi','Only if you intentionally leave later; otherwise save the appetite for Osaka.')]},
 {name:'Kamishikimi → Fukuoka exit',time:'10:55–18:30',mode:'driving',img:XIMG.takachiho,summary:'Kamishikimi is the one protected forest shrine. After that, logistics win: car return, Hakata, Shinkansen.',extras:[xp('Ugeto-Iwa',32.8060,131.1750,'bonus','Continue above the shrine only if the stone path is dry and you are ahead.')],food:[food('Service-area food','Today convenience beats culinary ambition until Osaka.')]},
 {name:'Osaka Friday night',time:'19:00–late',mode:'walking',img:XIMG.dotonbori,summary:'Check in fast and immediately work the Namba core on foot. Canal neon → food → Hozenji → bars.',extras:[xp('Hozenji Temple',34.6686,135.5031,'bonus','Tiny moss-covered temple inside the nightlife district; perfect five-minute contrast.'),xp('Hozenji Yokocho',34.6685,135.5029,'photo','Stone alley beside the temple; more atmospheric than another lap of the Glico sign.'),xp('Shinsaibashi-suji',34.6724,135.5010,'bonus','Covered shopping/night corridor north from Dotonbori.'),xp('Amerikamura',34.6712,135.4982,'bonus','Youth/streetwear/bar district; use only if the group still has energy.')],food:[food('Mizuno','Famous okonomiyaki in Dotonbori; skip if the line is brutal.'),food('Takoyaki Wanaka','Reliable takoyaki target in Namba.'),food('Kushikatsu Daruma Namba','Easy kushikatsu option without leaving the core.')]}
],
'2026-09-26':[
 {name:'Himeji Castle district',time:'08:20–11:35',mode:'walking',img:XIMG.himeji,summary:'Walk the straight Otemae-dori approach so the castle grows in front of you, then pair the Main Keep with Koko-en rather than adding random museums.',extras:[xp('Sannomaru Square',34.8378,134.6935,'photo','Best wide exterior scale before/after the keep.'),xp('Himeji City Zoo exterior area',34.8373,134.6956,'bonus','Not a priority; only useful if a member of the group wants a quick break outside the castle route.')],food:[food('Himeji station ekiben','Best lunch strategy today: eat on the train to Kobe.')]},
 {name:'Shin-Kobe → Kitano',time:'12:50–15:35',mode:'walking',img:XIMG.kobe,summary:'Ropeway gives the city/sea scale; then walk downhill through Kitano so gravity helps you toward Chinatown.',extras:[xp('Nunobiki Waterfall',34.7096,135.1943,'bonus','Beautiful but creates extra stairs/time from Shin-Kobe. Add only if the ropeway line is short and the group wants nature.'),xp('Kitano Tenman Shrine',34.7056,135.1907,'bonus','Small hillside shrine with city view inside the Kitano zone.'),xp('Ikuta Shrine',34.6949,135.1907,'bonus','Central Kobe shrine near Sannomiya. Great quick add before dinner if timing opens.')],food:[food('Kitano cafés','One coffee maximum; the beef dinner is the anchor.')]},
 {name:'Nankinmachi → Harbor → Kobe beef',time:'16:00–19:30',mode:'walking',img:XIMG.kobe,summary:'Snack in Chinatown, walk west through Meriken/Harborland at golden hour, then return to Sannomiya for the real meal.',extras:[xp('BE KOBE Monument',34.6827,135.1890,'photo','Quick waterfront photo inside Meriken Park.'),xp('Kobe Port Tower',34.6826,135.1866,'bonus','Exterior is enough because you already got a mountain view at Nunobiki.'),xp('Mosaic Ferris Wheel',34.6793,135.1811,'bonus','Harborland color after sunset; ride only if the group actively wants it.')],food:[food('Roushouki','Historic butaman shop in Nankinmachi.'),food('YUNYUN','Fried xiaolongbao and Chinatown snacks.'),food('Kobe Plaisir','Strong reservation target for a proper Kobe beef teppanyaki dinner near Sannomiya.')]}
],
'2026-09-27':[
 {name:'Kinkaku → Ryoanji',time:'10:15–11:55',mode:'walking',img:XIMG.kinkaku,summary:'Two compact temple loops. Do not let souvenir stalls expand the schedule.',extras:[xp('Ninna-ji',35.0310,135.7138,'detour','UNESCO temple west of Ryoan-ji. Beautiful, but only add if you intentionally cut Arashiyama flex.'),xp('Ryoan-ji Kyoyochi Pond',35.0347,135.7180,'bonus','Do the pond/garden on your way out after the rock garden; it is part of the same loop.')],food:[food('Quick lunch en route to Arashiyama','Taxi/bus time matters more than a famous lunch here.')]},
 {name:'Arashiyama conquest',time:'12:45–16:15',mode:'walking',img:XIMG.arashiyama,summary:'Tenryu-ji garden → Bamboo Grove → optional northern temples/garden → Togetsukyo. The entire area is walkable; choose extras based on crowd/energy.',extras:[xp('Okochi Sanso Garden',35.0177,135.6694,'bonus','Excellent landscaped villa/garden immediately above the bamboo grove; one of the best “if ahead” adds.'),xp('Jojakko-ji',35.0197,135.6684,'bonus','Forest hillside temple; quieter than the central bamboo corridor.'),xp('Nison-in',35.0218,135.6665,'bonus','Temple with a photogenic approach north of the grove.'),xp('Kimono Forest',35.0152,135.6783,'bonus','Quick art/light installation beside Randen Arashiyama Station.'),xp('Arashiyama Park Nakanoshima',35.0118,135.6760,'bonus','River/island angle on Togetsukyo and the mountain backdrop.')],food:[food('Oimatsu Arashiyama','Warabi mochi / seasonal wagashi very close to Tenryu-ji and bamboo.'),food('Arashiyama Yoshimura','Soba with river/bridge access; good if there is no long wait.'),food('% Arabica Arashiyama','Photogenic riverside coffee; only if the queue is short.')]},
 {name:'Yasaka → Gion → Pontocho',time:'17:20–late',mode:'walking',img:XIMG.gion,summary:'This is about streets and atmosphere, not more ticket counters. Move from shrine lanterns through the geisha district to the river and dinner.',extras:[xp('Shinbashi-dori',35.0060,135.7766,'photo','One of Gion’s prettiest preserved streets; use it to connect Shirakawa to the nightlife core.'),xp('Kennin-ji',35.0007,135.7736,'bonus','Major Zen temple near Hanamikoji. Only add before closing if you cross the area early.'),xp('Tatsumi Bridge',35.0062,135.7758,'photo','Tiny Gion Shirakawa photo anchor.'),xp('Kamo River Shijo Bridge',35.0038,135.7706,'bonus','Step to the river before/after Pontocho for open space and city lights.')],food:[food('Izuju','Traditional Kyoto-style pressed/mackerel sushi beside Yasaka; early dinner option.'),food('Pontocho Chikarayama','Premium wagyu sukiyaki/shabu-shabu option if you want a reservation dinner.'),food('Random Pontocho alley izakaya','For eight people, visible seating and a manageable wait matter more than fame.')]}
],
'2026-09-28':[
 {name:'Kiyomizu → Higashiyama',time:'06:00–08:45',mode:'walking',img:'https://oceanjar-new.s3.ap-south-1.amazonaws.com/Kiyomizu_dera_26dc0a16bf.jpg',summary:'The early start is for empty architecture. Shoot first, shop later. Walk downhill rather than reversing back up the slopes.',extras:[xp('Otowa Waterfall',34.9945,135.7854,'bonus','Inside Kiyomizu; do it before exiting if the queue is short.'),xp('Yasaka Koshindo',34.9980,135.7799,'bonus','Tiny colorful temple directly by the preserved lanes; easy five-minute add.'),xp('Hokan-ji / Yasaka Pagoda',34.9986,135.7808,'photo','Exterior photo anchor above the lanes.'),xp('Ishibe-koji',35.0005,135.7796,'bonus','Short preserved stone lane near Yasaka; one of the best quiet connectors toward Gion.')],food:[food('Ichikawaya Coffee','Excellent machiya roastery near the wider Kiyomizu area, but opens around 08:00; use only if timing naturally fits.'),food('% Arabica Kyoto Higashiyama','Coffee option by the historic lanes; skip a long queue.')]},
 {name:'Nanzen-ji → Philosopher’s Path → Ginkaku',time:'09:00–11:25',mode:'walking',img:XIMG.nanzen,summary:'This is a northbound scenic chain. The aqueduct and temple grounds lead naturally into the canal walk and Ginkaku — never turn it into three separate transit legs.',extras:[xp('Suirokaku Aqueduct',35.0111,135.7949,'photo','The brick arches are inside the Nanzen-ji grounds; absolutely include this.'),xp('Eikan-do',35.0144,135.7956,'bonus','Beautiful temple/garden beside the route. Better in fall foliage season; cut on this max day unless you are ahead.'),xp('Honen-in',35.0218,135.7968,'bonus','Quiet mossy gate just off Philosopher’s Path; ideal 10-minute bonus with minimal detour.')],food:[food('Philosopher’s Path cafés','Use only for water/coffee if there is no wait; Nishiki is lunch.')]},
 {name:'Nishiki → Central Kyoto',time:'12:00–late',mode:'walking',img:XIMG.nishiki,summary:'Eat through Nishiki, then decide if Nijo is worth the westward move. Evening naturally falls back toward Kamo/Pontocho.',extras:[xp('Teramachi Shopping Arcade',35.0061,135.7675,'bonus','Covered arcade directly beside Nishiki; better for browsing than adding another distant attraction.'),xp('Shinkyogoku',35.0054,135.7677,'bonus','Parallel shopping lane; useful if rain or if the group wants souvenirs.'),xp('Honno-ji',35.0103,135.7689,'bonus','Historic temple north of the arcade, easy only if you walk that direction.'),xp('Ninomaru Garden',35.0142,135.7487,'bonus','Inside Nijo; prioritize the palace interior first, garden second.')],food:[food('Daiyasu Nishiki','Oyster/seafood stop in Nishiki.'),food('Soy milk donut / tofu stalls','Quick Kyoto snack; follow the market rule not to eat while walking.'),food('Pontocho / Kiyamachi','Best dinner zone because you are already returning east.')]}
],
'2026-09-29':[
 {name:'Fushimi Inari dawn',time:'05:30–07:10',mode:'walking',img:XIMG.fushimi,summary:'Lower torii first. Go higher only until the return-time math says turn around. You do not need the summit.',extras:[xp('Okusha Hohaisho',34.9668,135.7827,'photo','Classic torii density and first logical turnaround.'),xp('Yotsutsuji',34.9618,135.7911,'bonus','City overlook higher on the mountain; only if pace and heat are good.'),xp('Tofuku-ji',34.9760,135.7746,'detour','Excellent Zen complex nearby, but not compatible with the fixed 09:00 teamLab unless you intentionally change the day.')],food:[food('Konbini breakfast near apartment','Best move today. Do not build a breakfast wait before teamLab.')]},
 {name:'Shinjuku first night',time:'16:00–late',mode:'walking',img:XIMG.shinjuku,summary:'One district only. Skyline orientation → Omoide → neon Kabukicho → Hanazono → Golden Gai.',extras:[xp('Tokyu Kabukicho Tower',35.6950,139.7006,'bonus','Modern entertainment tower directly on the Kabukicho walk.'),xp('Shinjuku Central Park',35.6899,139.6907,'bonus','Next to the Metropolitan Government building; brief reset if you arrive early.'),xp('Shinjuku Southern Terrace',35.6886,139.7000,'bonus','City-light pedestrian deck south of the station; skip if it pulls you off the west→east flow.')],food:[food('Fuunji','Famous tsukemen west/southwest of Shinjuku Station; best before nightlife only if the line is reasonable.'),food('Ramen Hayashida','Strong Shinjuku ramen option near the east side.'),food('Omoide Yokocho yakitori','The location itself is the experience; choose a counter with visible seats.')]}
],
'2026-09-30':[
 {name:'Tsukiji breakfast',time:'07:15–08:45',mode:'walking',img:'https://images.unsplash.com/photo-1554797589-7241bb691973?auto=format&fit=crop&w=1400&q=80',summary:'One long line maximum. This is a moving breakfast, not a reservation meal.',extras:[xp('Tsukiji Hongwanji',35.6665,139.7726,'bonus','Striking temple across from the market; easy 10-minute architecture add.'),xp('Namiyoke Inari Shrine',35.6642,139.7683,'bonus','Tiny market-protector shrine on the edge of Tsukiji.'),xp('Hamarikyu Gardens',35.6597,139.7633,'detour','Excellent garden nearby, but it risks the fixed 10:00 Planets entry. Save unless schedule changes.')],food:[food('Yamachou','Tamagoyaki target in the market.'),food('Kitsuneya','Famous horumon-don; only if line is controlled.'),food('Seafood don / sushi stalls','Choose quality + short wait over internet fame.')]},
 {name:'Toyosu → Odaiba',time:'10:00–14:30',mode:'transit',img:XIMG.odaiba,summary:'Planets is fixed. After it, use the Yurikamome/elevated-city feeling, then Gundam and the waterfront. Do not get trapped inside malls.',extras:[xp('Toyosu Senkyaku Banrai',35.6469,139.7850,'bonus','New food/onsen complex near Toyosu market. Only add if Planets ends early.'),xp('Odaiba Marine Park',35.6294,139.7730,'bonus','Best open waterfront angle toward Rainbow Bridge.'),xp('Fuji TV Building',35.6265,139.7741,'bonus','Iconic futurist architecture behind the waterfront walk.')],food:[food('DiverCity food court','Efficiency move after Planets.'),food('Aqua City / Decks','Plenty of lunch options with bay access; do not overthink it.')]},
 {name:'Ginza → Marunouchi → Yurakucho',time:'15:15–late',mode:'walking',img:'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1400&q=80',summary:'Polished Tokyo ends under the tracks. Architecture first, then station views, then casual rail-arch food.',extras:[xp('Kabukiza',35.6694,139.7679,'bonus','Great exterior architecture on the Ginza route.'),xp('Ginza Itoya',35.6721,139.7668,'bonus','Legendary stationery store if your group cares; cap browsing.'),xp('Marunouchi Naka-dori',35.6800,139.7639,'bonus','Elegant pedestrian/retail street running beside Tokyo Station.'),xp('Tokyo International Forum',35.6769,139.7634,'bonus','Glass architecture between Marunouchi and Yurakucho.')],food:[food('Ginza Kagari','Chicken paitan ramen; useful if you want a compact meal before Marunouchi.'),food("Andy's Shin Hinomoto",'Classic under-the-tracks izakaya option in Yurakucho; good fit for the day’s final zone.'),food('Random Yurakucho rail-arch izakaya','For eight people, immediate seating wins.')]}
],
'2026-10-01':[
 {name:'Kegon + Lake Chuzenji',time:'09:15–10:45',mode:'transit',img:'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=1400&q=80',summary:'Mountain visibility first. Do the falls, then a short lake walk; never spend the morning shopping.',extras:[xp('Chuzenji Temple',36.7334,139.4877,'bonus','Lakefront Buddhist temple, but it adds bus/walk time west of the core.'),xp('Futarasan Chugushi',36.7402,139.4936,'bonus','Shrine by the lake; only if bus timing is generous.')],food:[food('Yuba / soba near Chuzenji','Quick lunch only; the downhill bus buffer matters more.')]},
 {name:'Nikko World Heritage cluster',time:'12:15–15:50',mode:'walking',img:XIMG.nikko,summary:'Toshogu is the anchor. Futarasan and Rinnoji sit naturally beside it, then walk downhill to Shinkyo.',extras:[xp('Taiyuin',36.7587,139.5942,'bonus','Rinnoji sub-complex / mausoleum west of Futarasan; excellent but time-expensive.'),xp('Kanmangafuchi Abyss',36.7540,139.5859,'detour','Atmospheric river path with rows of Jizo. Strong bonus if the group wants nature and can give it ~30–45 minutes.')],food:[food('Nikko yuba cuisine','Local specialty; grab it near the station or heritage zone only if seating is immediate.'),food('Nikko soba','Fast, local and easy before the return train.')]}
],
'2026-10-02':[
 {name:'Hase / West Kamakura',time:'08:00–09:35',mode:'walking',img:XIMG.kamakura,summary:'Hase-dera gives garden + ocean; Great Buddha gives scale. They are close enough to treat as one walkable block.',extras:[xp('Goryo Shrine Kamakura',35.3103,139.5303,'bonus','Small shrine by the Enoden tracks close to Hase; charming if you are ahead.'),xp('Yuigahama Beach',35.3087,139.5375,'bonus','Fast ocean touch between Hase and central Kamakura only if weather is great.')],food:[food('Matsubara-an','Excellent soba in an old house near Yuigahama; opens later, so it does not fit the early Hase block unless you change lunch timing.')]},
 {name:'Hokokuji → Tsurugaoka → Komachi',time:'10:05–12:45',mode:'walking',img:XIMG.kamakura,summary:'Bamboo calm first, then the major shrine axis, then let Komachi be lunch and shopping on the way out.',extras:[xp('Jomyo-ji',35.3230,139.5734,'bonus','Zen temple very close to Hokokuji; add only if the bamboo stop is moving quickly.'),xp('Wakamiya Oji',35.3197,139.5535,'bonus','Grand approach from the station toward Tsurugaoka; walk a segment if crowd flow allows.'),xp('Dankazura',35.3220,139.5548,'photo','Raised central approach inside Wakamiya Oji leading to the shrine.')],food:[food('Caraway Kamakura','Classic curry near Komachi; popular, so do not wait forever.'),food('Kamakura ChaCha','Matcha gelato/sweets for a quick dessert.'),food('Shirasu-don shops','Local whitebait specialty; availability can depend on catch.')]},
 {name:'Azabudai → Tokyo Tower',time:'16:30–19:15',mode:'walking',img:'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=1400&q=80',summary:'Borderless is the fixed gate. Afterward, walk the old-new contrast toward Zojoji and Tokyo Tower.',extras:[xp('Shiba Park',35.6566,139.7484,'bonus','Best open-space framing of Tokyo Tower near Zojoji.'),xp('Atago Shrine',35.6647,139.7486,'bonus','Steep staircase shrine north of Azabudai; add only before Borderless if you arrive early.')],food:[food('Azabudai Hills restaurants','Convenient pre/post-Borderless dinner options.'),food('Roppongi nightlife dinner','Better if the group already decides to party in Roppongi.')]}
],
'2026-10-03':[
 {name:'Meiji → Harajuku → Omotesando',time:'08:30–11:30',mode:'walking',img:XIMG.meiji,summary:'Forest to youth culture to architecture. The contrast is the point; keep moving south/east.',extras:[xp('Meiji Jingu Sake Barrels',35.6737,139.6977,'photo','Easy photo point on the forest approach.'),xp('Tokyu Plaza Harajuku Harakado',35.6697,139.7054,'bonus','Modern Harajuku architecture/retail right at the Omotesando junction.'),xp('Cat Street',35.6658,139.7047,'bonus','Use the pedestrian side street as the stylish connector toward Omotesando rather than as separate shopping mission.')],food:[food('Harajuku crepe','One classic snack, no queue obsession.'),food('Omotesando coffee','Pick whichever good café has seats now.')]},
 {name:'Aoyama → Daikanyama → Nakameguro',time:'11:40–14:45',mode:'transit',img:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1400&q=80',summary:'This is design Tokyo: museum garden, low-rise Daikanyama, then the Meguro River neighborhood scale.',extras:[xp('Log Road Daikanyama',35.6507,139.7026,'bonus','Low-rise pedestrian development on the way through Daikanyama.'),xp('Saigoyama Park',35.6475,139.6953,'bonus','Small hilltop park between Daikanyama and Nakameguro.'),xp('Starbucks Reserve Roastery Tokyo',35.6491,139.6920,'bonus','Architecturally impressive Nakameguro coffee destination; huge time sink if there is a wait.')],food:[food('Daikanyama cafés','Better lunch zone than Harajuku if the group wants calm.'),food('Nakameguro ramen / izakaya','Good neighborhood lunch; choose immediate seating.')]},
 {name:'Shibuya street → Sky → party',time:'15:00–late',mode:'walking',img:XIMG.shibuya,summary:'Stay in one compact radius. Street level first, then Sky at the booked time, then nightlife with no commute.',extras:[xp('Hachiko',35.6591,139.7006,'photo','Five-minute landmark directly at the crossing.'),xp('Miyashita Park',35.6616,139.7018,'bonus','Rooftop/retail park; useful while waiting for your Sky slot.'),xp('Shibuya PARCO',35.6621,139.6987,'bonus','Nintendo/anime/fashion floors if the group actively wants them.'),xp('Nonbei Yokocho',35.6607,139.7021,'bonus','Tiny old-school drinking alley under the tracks; good contrast after Sky.')],food:[food('Uobei Shibuya Dogenzaka','Fast conveyor-style sushi, easy for groups when queue is manageable.'),food('Sushi no Midori Shibuya','Very popular; quality can be worth it but the wait can wreck the evening.'),food('Center-gai ramen / izakaya','Use live seating and keep the night moving.')]}
],
'2026-10-04':[
 {name:'Asakusa dawn',time:'06:15–07:25',mode:'walking',img:XIMG.sensoji,summary:'Treat the entire temple complex as a sequence: Kaminarimon → quiet Nakamise → Hozomon → Senso-ji → Asakusa Shrine.',extras:[xp('Kaminarimon',35.7112,139.7964,'photo','Start gate; much cleaner photos before the shopping street wakes.'),xp('Hozomon',35.7140,139.7966,'photo','Second giant gate before the main hall.'),xp('Asakusa Shrine',35.7152,139.7976,'bonus','Directly beside Senso-ji and easy to miss; always include if open access is clear.')],food:[food('Konbini / early café','Most famous Asakusa food is not open this early — that is intentional.')]},
 {name:'Yanaka → Nezu → Ueno → Ameyoko',time:'08:05–11:15',mode:'walking',img:'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=1400&q=80',summary:'Old low-rise Tokyo into shrine greenery, then the city scale rises as you hit Ueno and the market.',extras:[xp('Yuyake Dandan',35.7274,139.7654,'photo','Staircase overlook at the entrance to Yanaka Ginza.'),xp('Yanaka Cemetery',35.7217,139.7711,'bonus','Quiet old-Tokyo lanes; use only a short edge segment.'),xp('Shinobazu Pond',35.7118,139.7720,'bonus','Fast Ueno landscape add, especially if lotus scenery is good.')],food:[food('Ameyoko snacks','Seafood skewers, fruit, street-market bites. Eat standing where allowed; keep moving.')]},
 {name:'Kappabashi → Asakusa daytime → Sumida',time:'11:30–15:30',mode:'walking',img:XIMG.sensoji,summary:'Now return to the same Asakusa core while it is alive. This is one of the rare deliberate repeats: morning for architecture, midday for culture/food.',extras:[xp('Asakusa Culture Tourist Information Center',35.7107,139.7960,'bonus','Free upper-floor view over Nakamise/Senso-ji — one of the best low-effort viewpoints.'),xp('Sumida Park',35.7135,139.8025,'bonus','Riverbank skyline walk toward Skytree.'),xp('Kappabashi Dougu Street giant chef',35.7133,139.7894,'photo','Iconic kitchenware-street landmark.')],food:[food('Daikokuya Tempura','Classic Asakusa tempura; likely queue, so use only if timing is comfortable.'),food('Asakusa Menchi','Fast fried snack on the Nakamise side streets.'),food('Sometaro','Old-school okonomiyaki in Asakusa if you want a sit-down lunch.')]},
 {name:'Skytree → Akihabara finale',time:'16:15–20:30',mode:'transit',img:XIMG.akihabara,summary:'Stay at Skytree through lights, then use Akihabara for the final high-energy Tokyo night.',extras:[xp('Tokyo Solamachi',35.7100,139.8107,'bonus','Retail/food base under Skytree; use for dinner only if you want to eat before Akihabara.'),xp('Sumida Aquarium',35.7104,139.8106,'bonus','High-quality aquarium under Skytree, but only if weather kills the view or you intentionally arrive early.'),xp('Kanda Myojin',35.7020,139.7682,'bonus','Historic shrine just west of Akihabara — perfect cultural contrast if you reach the area before it is too late.'),xp('Radio Kaikan',35.6989,139.7712,'bonus','Dense anime/hobby building right outside Akihabara Station.'),xp('GiGO Akihabara',35.6986,139.7718,'bonus','Arcade stop for the neon/gaming experience.')],food:[food('Gyukatsu Ichi Ni San','Popular beef cutlet in Akihabara; watch the wait.'),food('Akihabara ramen','Choose a strong nearby shop with immediate seats; tonight is about the district, not a destination meal.')]}
],
'2026-10-05':[
 {name:'Departure day',time:'TBD',mode:'transit',img:XIMG.shibuya,summary:'Do nothing ambitious until the airport transfer is locked backward from airline check-in.',extras:[],food:[food('Breakfast near hotel','Keep it local and stress-free.')]}]
};
window.EXPLORE_DATA={XIMG,ZONES};