(function(){
'use strict';
const DAYS=(window.TRIP_DATA&&window.TRIP_DATA.DAYS)||[],ZONES=(window.EXPLORE_DATA&&window.EXPLORE_DATA.ZONES)||{};
const $=s=>document.querySelector(s),$$=s=>Array.prototype.slice.call(document.querySelectorAll(s));
let di=0,manual=-1,map=null,mapReady=false,layers=[],userMarker=null;let done=new Set();try{done=new Set(JSON.parse(localStorage.getItem('jp10.done')||'[]'))}catch(e){}
const coords=o=>o&&Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng));
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1800)}
function dateKey(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return''}}
function mins(t){if(!/^\d{2}:\d{2}$/.test(t||''))return null;const a=t.split(':').map(Number);return a[0]*60+a[1]}
function jmins(){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return Number(p.find(x=>x.type==='hour').value)*60+Number(p.find(x=>x.type==='minute').value)}catch(e){return 0}}
function active(){if(manual>=0)return manual;const d=DAYS[di];if(!d||d.date!==dateKey())return 0;let x=0,n=jmins();d.stops.forEach((s,i)=>{const m=mins(s.time);if(m!==null&&n>=m)x=i});return x}
function autoDay(){const i=DAYS.findIndex(d=>d.date===dateKey());return i>=0?i:0}
function pin(o){return coords(o)?'https://www.google.com/maps?q='+o.lat+','+o.lng:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((o.name||'')+' Japan')}
function directions(o){if(!coords(o))return pin(o);const mode=/DRIVE|TRAIN|MOVE|LOGISTICS/.test(o.type||'')?'driving':'walking';return 'https://www.google.com/maps/dir/?api=1&destination='+o.lat+','+o.lng+'&travelmode='+mode}
function search(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q+' Japan')}
function embed(o){return coords(o)?'https://www.google.com/maps?q='+o.lat+','+o.lng+'&z=16&output=embed':''}
function clean(name,city){return ((name||'').replace(/·.*$/,'').replace(/→/g,' ').replace(/speed lunch|dinner|check-in|retrieve luggage|nightlife/gi,'').trim()+' '+(city||'')+' Japan').trim()}
const ZQ=[[/Arashiyama/i,'Arashiyama'],[/Kinkaku|Ryoan|Ninna/i,'Kinkaku-ji Kyoto'],[/Yasaka|Gion|Pontocho|Chion/i,'Gion Kyoto'],[/Kiyomizu|Higashiyama/i,'Kiyomizu-dera'],[/Nanzen|Philosopher|Ginkaku|Honen/i,'Nanzen-ji'],[/Nishiki|Teramachi|Nijo/i,'Nishiki Market Kyoto'],[/Fushimi/i,'Fushimi Inari-taisha'],[/Minami|Dotonbori|Shinsaibashi|Namba|Shinsekai/i,'Dotonbori Osaka'],[/Himeji/i,'Himeji Castle'],[/Kobe|Nunobiki|Nankinmachi/i,'Kobe Japan'],[/Nagasaki|Glover|Dejima|Ryoma|Urakami/i,'Nagasaki Japan'],[/Yufuin/i,'Yufuin'],[/Beppu|Kannawa/i,'Beppu'],[/Aso|Kuju|Yamanami/i,'Mount Aso'],[/Takachiho/i,'Takachiho Gorge'],[/Shinjuku/i,'Shinjuku'],[/Tsukiji/i,'Tsukiji'],[/Odaiba|Toyosu/i,'Odaiba'],[/Ginza|Marunouchi/i,'Ginza Tokyo'],[/Nikko|Chuzenji|Kegon/i,'Nikko Japan'],[/Kamakura|Hase/i,'Kamakura'],[/Shibuya|Harajuku|Meiji|Daikanyama/i,'Shibuya'],[/Asakusa|Senso|Yanaka|Ueno|Skytree|Akihabara/i,'Senso-ji']];
function zquery(z,d){for(const q of ZQ)if(q[0].test(z.name))return q[1];return clean(z.name,d.city)}
async function wimg(q){if(!q)return'';const k='jp10:'+q;try{const c=sessionStorage.getItem(k);if(c!==null)return c}catch(e){}try{const u='https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrnamespace=0&gsrlimit=1&gsrsearch='+encodeURIComponent(q)+'&prop=pageimages&piprop=thumbnail&pithumbsize=1200&format=json&origin=*';const r=await fetch(u),j=await r.json(),p=j.query&&j.query.pages?Object.values(j.query.pages):[],src=p[0]&&p[0].thumbnail?p[0].thumbnail.source:'';try{sessionStorage.setItem(k,src)}catch(e){}return src}catch(e){return''}}
function photo(el,q,fb){if(!el)return;el.classList.add('loading');wimg(q).then(x=>x||wimg(fb)).then(src=>{el.classList.remove('loading');if(src)el.style.backgroundImage='url("'+src+'")';else el.style.background='linear-gradient(135deg,#e2e8f0,#f8fafc)'})}
function renderRail(){const r=$('#dayRail');r.innerHTML='';DAYS.forEach((d,i)=>{const b=document.createElement('button');b.className='daybtn'+(i===di?' active':'');b.textContent=d.short+' · '+d.city.split(' · ')[0].split(' → ')[0];b.onclick=()=>setDay(i);r.appendChild(b)});setTimeout(()=>r.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'}),30)}
function setDay(i){if(!DAYS[i])return;di=i;manual=-1;try{localStorage.setItem('jp10.day',String(i))}catch(e){}renderAll();panel('today');window.scrollTo({top:0,behavior:'smooth'})}
function renderHead(){const d=DAYS[di],zs=ZONES[d.date]||[];$('#dayDate').textContent='DAY '+(di+1)+' · '+d.short;$('#dayTitle').textContent=d.city;$('#dayMission').textContent=d.mission;$('#sleepMeta').textContent='Sleep: '+d.sleep;$('#stopCountMeta').textContent=d.stops.length+' planned stops';$('#zoneCountMeta').textContent=zs.length+' route areas'}
function renderStatus(){const d=DAYS[di],i=active(),s=d.stops[i]||d.stops[0],n=d.stops[Math.min(i+1,d.stops.length-1)]||s;$('#nowName').textContent=s.name;$('#nowDesc').textContent=s.desc;$('#nextName').textContent=n.name;$('#nextTime').textContent=(n.time||'')+(n.end?'–'+n.end:'');$('#nextDir').href=directions(n)}
function areaPreview(){const d=DAYS[di],r=$('#areaStrip'),zs=ZONES[d.date]||[];r.innerHTML='';zs.forEach((z,i)=>{const a=document.createElement('article');a.className='areamini';a.innerHTML='<div class="imgbox"></div><div class="body"><small>'+z.time+'</small><h3>'+z.name+'</h3><p>'+z.summary+'</p><div class="microstats">'+((z.sequence||[]).length?'<span>'+z.sequence.length+' route points</span>':'')+((z.extras||[]).length?'<span>+'+z.extras.length+' extras</span>':'')+'</div><button>Open full area plan</button></div>';photo(a.querySelector('.imgbox'),zquery(z,d),clean(d.city,d.city));a.querySelector('button').onclick=()=>{panel('areas');setTimeout(()=>$('#area-'+i)?.scrollIntoView({behavior:'smooth',block:'start'}),80)};r.appendChild(a)})}
function timeline(){const d=DAYS[di],r=$('#timeline');r.innerHTML='';d.stops.forEach((s,i)=>{const k=d.date+':'+i,a=document.createElement('article');a.className='stop'+(i===active()?' current':'');a.innerHTML='<div class="stoptime">'+s.time+'<small>'+(s.end||'')+'</small></div><div class="imgbox stopimg"></div><div class="stopcopy"><h3>'+s.name+'</h3><p>'+s.desc+'</p><div class="stopmeta"><span class="tag '+(s.priority==='MUST'?'must':'')+' '+(s.priority==='BOOK'?'book':'')+'">'+s.priority+'</span><span class="tag">'+s.type+'</span></div><div class="stoptools"><button class="details">Full details</button><a target="_blank" href="'+directions(s)+'">Directions</a><button class="mark '+(done.has(k)?'done':'')+'">'+(done.has(k)?'Done':'Mark done')+'</button></div></div>';photo(a.querySelector('.stopimg'),clean(s.name,d.city),clean(d.city,d.city));a.querySelector('.details').onclick=()=>openPlace(s,i);a.querySelector('.mark').onclick=()=>{done.has(k)?done.delete(k):done.add(k);localStorage.setItem('jp10.done',JSON.stringify(Array.from(done)));timeline()};r.appendChild(a)})}
function routeRows(z){return (z.sequence||[]).map((x,i)=>'<div class="routepoint"><div class="rnum">'+(i+1)+'</div><div><div class="rtitle"><h4>'+x.name+'</h4><span>'+(x.minutes||'')+'</span></div><p>'+x.note+'</p><div class="rlinks"><a target="_blank" href="'+(coords(x)?directions(x):search(x.name))+'">Directions ↗</a>'+(coords(x)?'<a target="_blank" href="'+pin(x)+'">Pin ↗</a>':'')+'</div></div></div>').join('')}
function extraRows(a){return (a||[]).map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" href="'+(coords(x)?directions(x):search(x.q||x.name))+'">Map</a></div>').join('')}
function foodRows(a){return (a||[]).map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" href="'+search(x.q||x.name)+'">Find</a></div>').join('')}
function areas(){const d=DAYS[di],r=$('#areas'),zs=ZONES[d.date]||[];r.innerHTML='';zs.forEach((z,i)=>{const a=document.createElement('article');a.className='area';a.id='area-'+i;const rr=routeRows(z),er=extraRows(z.extras),fr=foodRows(z.food);a.innerHTML='<div class="imgbox areaimg"></div><div class="areacontent"><small>'+z.time+' · '+(z.mode||'')+'</small><h2>'+z.name+'</h2><p class="areasummary">'+z.summary+'</p>'+(z.strategy?'<div class="expertcall"><b>ROUTE LOGIC</b><p>'+z.strategy+'</p></div>':'')+(rr?'<div class="subsection"><h3>DO THIS IN ORDER</h3>'+rr+'</div>':'')+(z.photo?'<div class="expertcall photo"><b>PHOTO PLAN</b><p>'+z.photo+'</p></div>':'')+(z.cut?'<div class="expertcall cut"><b>IF YOU ARE LATE</b><p>'+z.cut+'</p></div>':'')+(z.rules?'<div class="expertcall rules"><b>IMPORTANT</b><p>'+z.rules+'</p></div>':'')+(er?'<div class="subsection"><h3>EXTRA PINS WORTH KNOWING</h3>'+er+'</div>':'')+(fr?'<div class="subsection"><h3>FOOD THAT FITS THIS ROUTE</h3>'+fr+'</div>':'')+'</div>';photo(a.querySelector('.areaimg'),zquery(z,d),clean(d.city,d.city));r.appendChild(a)})}
function trip(){const r=$('#tripGrid');r.innerHTML='';DAYS.forEach((d,i)=>{const x=document.createElement('article');x.className='tripday';x.innerHTML='<small>'+d.short+' · DAY '+(i+1)+'</small><h3>'+d.city+'</h3><p>'+d.title+'<br><b>Sleep:</b> '+d.sleep+'</p><button>Open day</button>';x.querySelector('button').onclick=()=>setDay(i);r.appendChild(x)})}
function ensureMap(){if(mapReady)return true;if(!window.L)return false;map=L.map('map',{zoomControl:false});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);mapReady=true;return true}
function clear(){layers.forEach(m=>{try{m.remove()}catch(e){}});layers=[]}
function addMarker(o,html,style,bounds){if(!coords(o))return;bounds.push([o.lat,o.lng]);const ic=L.divIcon({className:'',html:'<div class="'+style+'">'+html+'</div>',iconSize:[28,28],iconAnchor:[14,14]});const m=L.marker([o.lat,o.lng],{icon:ic}).addTo(map).bindPopup('<div class="popup"><b>'+o.name+'</b><p>'+(o.desc||o.note||'')+'</p><a target="_blank" href="'+directions(o)+'">Directions ↗</a></div>');layers.push(m)}
function renderMap(){if(!ensureMap()){toast('Map did not load — every place still has Google Maps directions.');return}clear();const d=DAYS[di],zs=ZONES[d.date]||[],bounds=[];d.stops.forEach((s,i)=>addMarker(s,String(i+1),'planpin',bounds));let seen=new Set(d.stops.filter(coords).map(s=>Number(s.lat).toFixed(4)+','+Number(s.lng).toFixed(4)));zs.forEach(z=>{(z.sequence||[]).forEach(x=>{if(!coords(x))return;const k=Number(x.lat).toFixed(4)+','+Number(x.lng).toFixed(4);if(seen.has(k))return;seen.add(k);addMarker(x,'•',/photo/i.test(x.type||'')?'photopin':'routepin',bounds)});(z.extras||[]).forEach(x=>{if(!coords(x))return;const k=Number(x.lat).toFixed(4)+','+Number(x.lng).toFixed(4);if(seen.has(k))return;seen.add(k);addMarker(x,'+',/skip/i.test(x.type||'')?'skippin':'extrapin',bounds)})});if(bounds.length)map.fitBounds(bounds,{padding:[28,28],maxZoom:14});setTimeout(()=>map.invalidateSize(),80)}
function zoneFor(i){const d=DAYS[di],zs=ZONES[d.date]||[],s=d.stops[i],sm=mins(s.time);if(!zs.length)return null;let z=zs[0];zs.forEach(x=>{const m=mins((x.time||'').slice(0,5));if(m!==null&&sm!==null&&sm>=m)z=x});return z}
function openPlace(s,i){const d=DAYS[di],z=zoneFor(i);$('#drawer').classList.add('open');$('#backdrop').classList.add('open');$('#drawerName').textContent=s.name;$('#drawerMeta').textContent=(s.time||'')+(s.end?'–'+s.end:'')+' · '+s.type+' · '+s.priority;$('#drawerDesc').textContent=s.desc;photo($('#drawerHero'),clean(s.name,d.city),clean(d.city,d.city));$('#drawerDir').href=directions(s);$('#drawerPin').href=pin(s);const f=$('#drawerMap');if(coords(s)){f.src=embed(s);f.hidden=false}else f.hidden=true;const seq=z&&z.sequence?(z.sequence||[]).filter(x=>x.name!==s.name).slice(0,6):[],ex=z&&z.extras?(z.extras||[]).slice(0,5):[];$('#drawerNearby').innerHTML=extraRows(seq.concat(ex));$('#drawerFood').innerHTML=foodRows(z&&z.food?z.food.slice(0,5):[])}
function closeDrawer(){$('#drawer').classList.remove('open');$('#backdrop').classList.remove('open');$('#drawerMap').src=''}
function panel(p){$$('.panel').forEach(x=>x.classList.remove('active'));$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.panel===p));$('#'+p+'Panel').classList.add('active');if(p==='map')setTimeout(renderMap,40);if(p==='areas')areas();window.scrollTo({top:0,behavior:'smooth'})}
function locate(){if(!navigator.geolocation)return toast('Location unavailable');navigator.geolocation.getCurrentPosition(pos=>{const d=DAYS[di],all=d.stops.map((x,i)=>({x,i}));(ZONES[d.date]||[]).forEach(z=>{(z.sequence||[]).concat(z.extras||[]).forEach(x=>all.push({x,i:null}))});let best={d:1e9};all.forEach(o=>{if(!coords(o.x))return;const dx=(pos.coords.latitude-o.x.lat)*111,dy=(pos.coords.longitude-o.x.lng)*90,v=Math.sqrt(dx*dx+dy*dy);if(v<best.d)best={...o,d:v}});if(!best.x)return toast('Could not match location');toast('Closest: '+best.x.name+' · '+best.d.toFixed(1)+' km');if(best.i!==null){manual=best.i;renderStatus();openPlace(best.x,best.i)}else{window.open(directions(best.x),'_blank')}if(mapReady){if(userMarker)userMarker.remove();userMarker=L.circleMarker([pos.coords.latitude,pos.coords.longitude],{radius:8,color:'#fff',weight:3,fillColor:'#34c759',fillOpacity:1}).addTo(map);map.setView([pos.coords.latitude,pos.coords.longitude],15)}},()=>toast('Allow location access when you are there'),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function renderSearch(q){const s=q.toLowerCase().trim(),out=[];if(s)DAYS.forEach((d,dx)=>{d.stops.forEach((x,si)=>{if((x.name+' '+x.desc+' '+d.city).toLowerCase().includes(s))out.push({d,dx,x,si,type:'stop'})});(ZONES[d.date]||[]).forEach(z=>{(z.sequence||[]).concat(z.extras||[]).forEach(x=>{if((x.name+' '+x.note+' '+z.name+' '+d.city).toLowerCase().includes(s))out.push({d,dx,x,type:'place'})});(z.food||[]).forEach(x=>{if((x.name+' '+x.note+' '+z.name+' '+d.city).toLowerCase().includes(s))out.push({d,dx,x,type:'food'})})})});$('#searchResults').innerHTML=out.slice(0,60).map((o,i)=>'<div class="searchresult" data-i="'+i+'"><b>'+o.x.name+'</b><small>'+o.d.short+' · '+o.d.city+' · '+o.type+'</small></div>').join('');$$('.searchresult').forEach((e,i)=>e.onclick=()=>{const o=out[i];di=o.dx;renderAll();$('#searchOverlay').classList.remove('open');if(o.type==='stop')openPlace(o.x,o.si);else window.open(o.type==='food'?search(o.x.q||o.x.name):directions(o.x),'_blank')})}
function renderAll(){renderRail();renderHead();renderStatus();areaPreview();timeline();trip();if($('#areasPanel').classList.contains('active'))areas();if(mapReady)renderMap()}
function bind(){$$('.navbtn').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$('#locateBtn').onclick=locate;$('#locateBtn2').onclick=locate;$('#resetNow').onclick=()=>{manual=-1;renderStatus();toast('Following itinerary')};$('#brandBtn').onclick=()=>setDay(autoDay());$('#closeDrawer').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#searchBtn').onclick=()=>{$('#searchOverlay').classList.add('open');setTimeout(()=>$('#searchInput').focus(),40)};$('#closeSearch').onclick=()=>$('#searchOverlay').classList.remove('open');$('#searchInput').oninput=e=>renderSearch(e.target.value)}
function init(){if(!DAYS.length)return;let s=Number(localStorage.getItem('jp10.day'));di=Number.isInteger(s)&&s>=0&&s<DAYS.length?s:autoDay();bind();renderAll();panel('today')}
document.addEventListener('DOMContentLoaded',init);
})();