(function(){
'use strict';
const DAYS=(window.TRIP_DATA&&window.TRIP_DATA.DAYS)||[];
const ZONES=(window.EXPLORE_DATA&&window.EXPLORE_DATA.ZONES)||{};
const $=s=>document.querySelector(s),$$=s=>Array.prototype.slice.call(document.querySelectorAll(s));
let dayIndex=0,manualStop=-1,map=null,mapReady=false,planLayer=[],extraLayer=[],userMarker=null;const done=new Set(JSON.parse(localStorage.getItem('jp9.done')||'[]'));
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.jp9toast);window.jp9toast=setTimeout(()=>e.classList.remove('show'),1700)}
function dateKey(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return''}}
function jstMinutes(){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return Number(p.find(x=>x.type==='hour').value)*60+Number(p.find(x=>x.type==='minute').value)}catch(e){return 0}}
function minOf(t){if(!/^\d{2}:\d{2}$/.test(t||''))return null;const a=t.split(':').map(Number);return a[0]*60+a[1]}
function activeStop(){const d=DAYS[dayIndex];if(manualStop>=0)return manualStop;if(!d||d.date!==dateKey())return 0;const n=jstMinutes();let ix=0;d.stops.forEach((s,i)=>{const m=minOf(s.time);if(m!==null&&n>=m)ix=i});return ix}
function key(i){return DAYS[dayIndex].date+':'+i}
function coords(o){return o&&Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng))}
function pinUrl(o){return coords(o)?'https://www.google.com/maps?q='+o.lat+','+o.lng:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(o.name+' Japan')}
function dirUrl(o){if(!coords(o))return pinUrl(o);let mode='walking';if(/DRIVE|TRAIN|MOVE|LOGISTICS/.test(o.type||''))mode='driving';return 'https://www.google.com/maps/dir/?api=1&destination='+o.lat+','+o.lng+'&travelmode='+mode}
function searchUrl(q){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q+' Japan')}
function embedUrl(o){return coords(o)?'https://www.google.com/maps?q='+o.lat+','+o.lng+'&z=16&output=embed':''}
function autoDay(){const k=dateKey(),i=DAYS.findIndex(d=>d.date===k);return i>=0?i:0}
function cleanQuery(name,city){let q=(name||'').replace(/·.*$/,'').replace(/→/g,' ').replace(/speed lunch|dinner|check-in|retrieve luggage|morning atmosphere|street layer|Friday|Saturday|nightlife/gi,'').trim();return q+' '+(city||'')+' Japan'}
const zoneWiki=[[/Ryoma|Urakami|Nagasaki/i,'Nagasaki'],[/Chinatown|Dejima|Glover/i,'Nagasaki'],[/Yufuin/i,'Yufuin'],[/Beppu|Kannawa/i,'Beppu'],[/Yamanami|Kuju/i,'Aso-Kuju National Park'],[/Kurokawa/i,'Kurokawa Onsen'],[/Aso/i,'Mount Aso'],[/Takachiho/i,'Takachiho Gorge'],[/Osaka|Dotonbori/i,'Dotonbori'],[/Himeji/i,'Himeji Castle'],[/Kobe/i,'Kobe'],[/Kinkaku/i,'Kinkaku-ji'],[/Arashiyama/i,'Arashiyama'],[/Gion|Yasaka/i,'Gion'],[/Kiyomizu|Higashiyama/i,'Kiyomizu-dera'],[/Nanzen|Philosopher/i,'Nanzen-ji'],[/Nishiki/i,'Nishiki Market'],[/Fushimi/i,'Fushimi Inari-taisha'],[/Shinjuku/i,'Shinjuku'],[/Tsukiji/i,'Tsukiji fish market'],[/Odaiba|Toyosu/i,'Odaiba'],[/Ginza|Marunouchi/i,'Ginza'],[/Nikko|Kegon|Chuzenji/i,'Nikkō'],[/Kamakura|Hase/i,'Kamakura'],[/Azabudai|Tokyo Tower/i,'Tokyo Tower'],[/Meiji|Harajuku|Omotesando/i,'Meiji Shrine'],[/Aoyama|Daikanyama|Nakameguro/i,'Daikanyama'],[/Shibuya/i,'Shibuya'],[/Asakusa|Senso/i,'Sensō-ji'],[/Yanaka|Nezu|Ueno/i,'Yanaka, Tokyo'],[/Kappabashi|Skytree|Akihabara/i,'Tokyo Skytree']];
function zoneQuery(z,d){for(const x of zoneWiki)if(x[0].test(z.name))return x[1];return cleanQuery(z.name,d.city)}
async function wikiImage(query){if(!query)return'';const ck='jp9img:'+query;try{const c=sessionStorage.getItem(ck);if(c!==null)return c}catch(e){}try{const u='https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrnamespace=0&gsrlimit=1&gsrsearch='+encodeURIComponent(query)+'&prop=pageimages&piprop=thumbnail&pithumbsize=1000&format=json&origin=*';const r=await fetch(u);const j=await r.json();const pages=j.query&&j.query.pages?Object.values(j.query.pages):[];const src=pages[0]&&pages[0].thumbnail?pages[0].thumbnail.source:'';try{sessionStorage.setItem(ck,src)}catch(e){}return src}catch(e){return''}}
function hydrateImage(el,q,fallback){if(!el)return;el.classList.add('loading');wikiImage(q).then(src=>{if(!src&&fallback)return wikiImage(fallback);return src}).then(src=>{el.classList.remove('loading');if(src)el.style.backgroundImage='url("'+src+'")';else el.style.background='linear-gradient(135deg,#dfe7ef,#f7f8fa)'})}
function renderRail(){const r=$('#dayRail');r.innerHTML='';DAYS.forEach((d,i)=>{const b=document.createElement('button');b.className='daybtn'+(i===dayIndex?' active':'');b.textContent=d.short+' · '+d.city.split(' · ')[0].split(' → ')[0];b.onclick=()=>setDay(i);r.appendChild(b)});setTimeout(()=>r.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'}),20)}
function setDay(i){if(!DAYS[i])return;dayIndex=i;manualStop=-1;localStorage.setItem('jp9.day',String(i));renderAll();switchPanel('today');window.scrollTo({top:0,behavior:'smooth'})}
function renderHeader(){const d=DAYS[dayIndex];$('#dayDate').textContent='DAY '+(dayIndex+1)+' · '+d.short;$('#dayTitle').textContent=d.city;$('#dayMission').textContent=d.mission;$('#sleepMeta').textContent='Sleep: '+d.sleep;$('#stopCountMeta').textContent=d.stops.length+' planned stops';$('#zoneCountMeta').textContent=(ZONES[d.date]||[]).length+' areas';}
function renderStatus(){const d=DAYS[dayIndex],i=activeStop(),s=d.stops[i]||d.stops[0],n=d.stops[Math.min(i+1,d.stops.length-1)]||s;$('#nowName').textContent=s.name;$('#nowDesc').textContent=s.desc;$('#nextName').textContent=n.name;$('#nextTime').textContent=(n.time||'')+(n.end?'–'+n.end:'');$('#nextDir').href=dirUrl(n);}
function renderAreasPreview(){const d=DAYS[dayIndex],zs=ZONES[d.date]||[],r=$('#areaStrip');r.innerHTML='';zs.forEach((z,zi)=>{const a=document.createElement('article');a.className='areamini';a.innerHTML='<div class="imgbox loading"></div><div class="body"><small>'+z.time+'</small><h3>'+z.name+'</h3><p>'+z.summary+'</p><button>Open area</button></div>';hydrateImage(a.querySelector('.imgbox'),zoneQuery(z,d),cleanQuery(d.city,d.city));a.querySelector('button').onclick=()=>{switchPanel('areas');setTimeout(()=>$('#area-'+zi)?.scrollIntoView({behavior:'smooth',block:'start'}),80)};r.appendChild(a)})}
function renderTimeline(){const d=DAYS[dayIndex],r=$('#timeline');r.innerHTML='';d.stops.forEach((s,i)=>{const a=document.createElement('article');a.className='stop';a.innerHTML='<div class="stoptime">'+s.time+'<small>'+(s.end||'')+'</small></div><div class="imgbox stopimg loading"></div><div class="stopcopy"><h3>'+s.name+'</h3><p>'+s.desc+'</p><div class="stopmeta"><span class="tag '+(s.priority==='MUST'?'must':'')+' '+(s.priority==='BOOK'?'book':'')+'">'+s.priority+'</span><span class="tag">'+s.type+'</span></div><div class="stoptools"><button class="details">Details</button><a target="_blank" rel="noopener" href="'+dirUrl(s)+'">Directions</a><button class="mark '+(done.has(key(i))?'done':'')+'">'+(done.has(key(i))?'Done':'Mark done')+'</button></div></div>';hydrateImage(a.querySelector('.stopimg'),cleanQuery(s.name,d.city),cleanQuery(d.city,d.city));a.querySelector('.details').onclick=()=>openPlace(s,i);a.querySelector('.mark').onclick=()=>{const k=key(i);done.has(k)?done.delete(k):done.add(k);localStorage.setItem('jp9.done',JSON.stringify(Array.from(done)));renderTimeline()};r.appendChild(a)})}
function zoneForStop(i){const d=DAYS[dayIndex],zs=ZONES[d.date]||[],s=d.stops[i];const sm=minOf(s.time);if(sm===null||!zs.length)return zs[0]||null;let chosen=zs[0];zs.forEach(z=>{const m=minOf((z.time||'').slice(0,5));if(m!==null&&sm>=m)chosen=z});return chosen}
function renderAreas(){const d=DAYS[dayIndex],zs=ZONES[d.date]||[],r=$('#areas');r.innerHTML='';zs.forEach((z,zi)=>{const a=document.createElement('article');a.className='area';a.id='area-'+zi;const extras=(z.extras||[]).map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" rel="noopener" href="'+(coords(x)?dirUrl(x):searchUrl(x.q||x.name))+'">Map</a></div>').join('');const foods=(z.food||[]).map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" rel="noopener" href="'+searchUrl(x.q||x.name)+'">Find</a></div>').join('');a.innerHTML='<div class="imgbox areaimg loading"></div><div class="areacontent"><small>'+z.time+' · '+(z.mode||'')+'</small><h2>'+z.name+'</h2><p>'+z.summary+'</p>'+(extras?'<div class="subsection"><h3>WORTH SEEING HERE</h3>'+extras+'</div>':'')+(foods?'<div class="subsection"><h3>FOOD THAT FITS THE ROUTE</h3>'+foods+'</div>':'')+'</div>';hydrateImage(a.querySelector('.areaimg'),zoneQuery(z,d),cleanQuery(d.city,d.city));r.appendChild(a)})}
function renderTrip(){const r=$('#tripGrid');r.innerHTML='';DAYS.forEach((d,i)=>{const x=document.createElement('article');x.className='tripday';x.innerHTML='<small>'+d.short+' · DAY '+(i+1)+'</small><h3>'+d.city+'</h3><p>'+d.title+'<br><b>Sleep:</b> '+d.sleep+'</p><button>Open day</button>';x.querySelector('button').onclick=()=>setDay(i);r.appendChild(x)})}
function ensureMap(){if(mapReady)return true;if(!window.L)return false;map=L.map('map',{zoomControl:false});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);mapReady=true;return true}
function clearMap(){planLayer.concat(extraLayer).forEach(m=>{try{m.remove()}catch(e){}});planLayer=[];extraLayer=[]}
function renderMap(){if(!ensureMap()){toast('Map failed to load. Use Directions on any place card.');return}clearMap();const d=DAYS[dayIndex],zs=ZONES[d.date]||[],bounds=[];d.stops.forEach((s,i)=>{if(!coords(s))return;bounds.push([s.lat,s.lng]);const ic=L.divIcon({className:'',html:'<div style="width:28px;height:28px;border-radius:50%;background:#0a84ff;color:#fff;border:3px solid #fff;box-shadow:0 3px 10px #0004;display:grid;place-items:center;font:800 10px -apple-system">'+(i+1)+'</div>',iconSize:[28,28],iconAnchor:[14,14]});const m=L.marker([s.lat,s.lng],{icon:ic}).addTo(map).bindPopup('<b>'+s.name+'</b><br><small>'+s.time+'–'+(s.end||'')+'</small><p>'+s.desc+'</p><a target="_blank" href="'+dirUrl(s)+'">Directions ↗</a>');planLayer.push(m)});zs.forEach(z=>(z.extras||[]).forEach(x=>{if(!coords(x))return;bounds.push([x.lat,x.lng]);const photo=/photo/i.test(x.type||'');const det=/detour/i.test(x.type||'');const bg=photo?'#15171a':'#fff',fg=photo?'#fff':'#15171a',bd=det?'#ff9f0a':'#15171a';const ic=L.divIcon({className:'',html:'<div style="width:24px;height:24px;border-radius:50%;background:'+bg+';color:'+fg+';border:2px solid '+bd+';box-shadow:0 3px 10px #0003;display:grid;place-items:center;font:800 13px -apple-system">+</div>',iconSize:[24,24],iconAnchor:[12,12]});const m=L.marker([x.lat,x.lng],{icon:ic}).addTo(map).bindPopup('<b>'+x.name+'</b><p>'+x.note+'</p><a target="_blank" href="'+dirUrl(x)+'">Directions ↗</a>');extraLayer.push(m)}));if(bounds.length)map.fitBounds(bounds,{padding:[28,28],maxZoom:14});setTimeout(()=>map.invalidateSize(),60)}
function openPlace(s,i){const d=DAYS[dayIndex],z=zoneForStop(i);$('#drawer').classList.add('open');$('#backdrop').classList.add('open');$('#drawerName').textContent=s.name;$('#drawerMeta').textContent=(s.time||'')+(s.end?'–'+s.end:'')+' · '+s.type+' · '+s.priority;$('#drawerDesc').textContent=s.desc;hydrateImage($('#drawerHero'),cleanQuery(s.name,d.city),cleanQuery(d.city,d.city));$('#drawerDir').href=dirUrl(s);$('#drawerPin').href=pinUrl(s);const iframe=$('#drawerMap');if(coords(s)){iframe.src=embedUrl(s);iframe.hidden=false}else{iframe.hidden=true}const extras=z&&z.extras?z.extras.slice(0,5):[];const foods=z&&z.food?z.food.slice(0,4):[];$('#drawerNearby').innerHTML=extras.length?extras.map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" href="'+(coords(x)?dirUrl(x):searchUrl(x.q||x.name))+'">Map</a></div>').join(''):'<p style="color:#6f7680;font-size:12px">No worthwhile add-ons needed here.</p>';$('#drawerFood').innerHTML=foods.length?foods.map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" href="'+searchUrl(x.q||x.name)+'">Find</a></div>').join(''):'<p style="color:#6f7680;font-size:12px">Keep moving and eat in the next food zone.</p>'}
function openExtra(x){$('#drawer').classList.add('open');$('#backdrop').classList.add('open');$('#drawerName').textContent=x.name;$('#drawerMeta').textContent='OPTIONAL · '+(x.type||'EXTRA');$('#drawerDesc').textContent=x.note;hydrateImage($('#drawerHero'),cleanQuery(x.name,DAYS[dayIndex].city),cleanQuery(DAYS[dayIndex].city,DAYS[dayIndex].city));$('#drawerDir').href=coords(x)?dirUrl(x):searchUrl(x.q||x.name);$('#drawerPin').href=coords(x)?pinUrl(x):searchUrl(x.q||x.name);const iframe=$('#drawerMap');if(coords(x)){iframe.src=embedUrl(x);iframe.hidden=false}else iframe.hidden=true;$('#drawerNearby').innerHTML='';$('#drawerFood').innerHTML=''}
function closeDrawer(){$('#drawer').classList.remove('open');$('#backdrop').classList.remove('open');$('#drawerMap').src=''}
function switchPanel(p){$$('.panel').forEach(x=>x.classList.remove('active'));$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.panel===p));$('#'+p+'Panel').classList.add('active');if(p==='map')setTimeout(renderMap,50);if(p==='areas')renderAreas();window.scrollTo({top:0,behavior:'smooth'})}
function locate(){if(!navigator.geolocation)return toast('Location unavailable');navigator.geolocation.getCurrentPosition(pos=>{const d=DAYS[dayIndex],all=d.stops.map((x,i)=>({x,i,kind:'plan'}));(ZONES[d.date]||[]).forEach(z=>(z.extras||[]).forEach(x=>all.push({x,kind:'extra'})));let best={dist:Infinity};all.forEach(o=>{if(!coords(o.x))return;const dx=(pos.coords.latitude-o.x.lat)*111,dy=(pos.coords.longitude-o.x.lng)*90,dist=Math.sqrt(dx*dx+dy*dy);if(dist<best.dist)best={...o,dist}});if(!best.x)return toast('Could not match your location');toast('Closest: '+best.x.name+' · '+best.dist.toFixed(1)+' km');if(best.kind==='plan'){manualStop=best.i;renderStatus();openPlace(best.x,best.i)}else openExtra(best.x);if(mapReady){if(userMarker)userMarker.remove();userMarker=L.circleMarker([pos.coords.latitude,pos.coords.longitude],{radius:8,color:'#fff',weight:3,fillColor:'#34c759',fillOpacity:1}).addTo(map);map.setView([pos.coords.latitude,pos.coords.longitude],15)}},()=>toast('Allow location access when you are in Japan'),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function buildSearch(q){const out=[];const s=q.toLowerCase().trim();if(!s)return out;DAYS.forEach((d,di)=>{d.stops.forEach((x,si)=>{if((x.name+' '+x.desc+' '+x.type+' '+d.city).toLowerCase().includes(s))out.push({kind:'stop',di,si,x,d})});(ZONES[d.date]||[]).forEach(z=>{(z.extras||[]).forEach(x=>{if((x.name+' '+x.note+' '+z.name+' '+d.city).toLowerCase().includes(s))out.push({kind:'extra',di,x,d})});(z.food||[]).forEach(x=>{if((x.name+' '+x.note+' '+z.name+' '+d.city).toLowerCase().includes(s))out.push({kind:'food',di,x,d})})})});return out.slice(0,50)}
function renderSearch(q){const out=buildSearch(q),r=$('#searchResults');r.innerHTML=out.map((o,i)=>'<div class="searchresult" data-i="'+i+'"><b>'+o.x.name+'</b><small>'+o.d.short+' · '+o.d.city+' · '+o.kind+'</small></div>').join('');$$('.searchresult').forEach((el,i)=>el.onclick=()=>{const o=out[i];dayIndex=o.di;renderAll();$('#searchOverlay').classList.remove('open');if(o.kind==='stop')openPlace(o.x,o.si);else if(o.kind==='extra')openExtra(o.x);else window.open(searchUrl(o.x.q||o.x.name),'_blank')})}
function renderAll(){renderRail();renderHeader();renderStatus();renderAreasPreview();renderTimeline();renderTrip();if($('#areasPanel').classList.contains('active'))renderAreas();if(mapReady)renderMap()}
function bind(){$$('.navbtn').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));$('#searchBtn').onclick=()=>{$('#searchOverlay').classList.add('open');setTimeout(()=>$('#searchInput').focus(),30)};$('#closeSearch').onclick=()=>$('#searchOverlay').classList.remove('open');$('#searchInput').oninput=e=>renderSearch(e.target.value);$('#closeDrawer').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#locateBtn').onclick=locate;$('#locateBtn2').onclick=locate;$('#resetNow').onclick=()=>{manualStop=-1;renderStatus();toast('Following the itinerary again')};$('#brandBtn').onclick=()=>{setDay(autoDay())}}
function init(){if(!DAYS.length){document.body.innerHTML='<main style="padding:30px;font-family:-apple-system"><h1>Trip data did not load.</h1><p>Refresh this page.</p></main>';return}const s=Number(localStorage.getItem('jp9.day'));dayIndex=Number.isInteger(s)&&s>=0&&s<DAYS.length?s:autoDay();bind();renderAll();switchPanel('today')}
document.addEventListener('DOMContentLoaded',init);
})();