(function(){
'use strict';
const DAYS=(window.TRIP_DATA&&window.TRIP_DATA.DAYS)||[],ZONES=(window.EXPLORE_DATA&&window.EXPLORE_DATA.ZONES)||{},AUD=window.JP_AUDIT||{};
const $=s=>document.querySelector(s),$$=s=>Array.prototype.slice.call(document.querySelectorAll(s));
const norm=AUD.norm||((s)=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim());
let di=0,manual=-1,map=null,mapReady=false,layers=[],routeLine=null,userMarker=null;let done=new Set();
try{done=new Set(JSON.parse(localStorage.getItem('jp12.done')||'[]'))}catch(e){}
const usedByIdentity=new Map(),usedImageUrls=new Map(),placeIndex=[];

function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__jpToast);window.__jpToast=setTimeout(()=>e.classList.remove('show'),2200)}
function dateKey(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return''}}
function jmins(){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return Number(p.find(x=>x.type==='hour').value)*60+Number(p.find(x=>x.type==='minute').value)}catch(e){return 0}}
function mins(t){const m=String(t||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function coords(o){return o&&Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng))}
function dayContext(d,z){const n=((z&&z.name)||'')+' '+(d&&d.city||'');if(/NAGASAKI/i.test(n))return'Nagasaki, Japan';if(/YUFUIN/i.test(n))return'Yufuin, Oita, Japan';if(/BEPPU|KANNAWA|KUJU|KOKONOE|YAMANAMI/i.test(n))return'Oita, Japan';if(/ASO|KUROKAWA|KAMISHIKIMI/i.test(n))return'Kumamoto, Japan';if(/TAKACHIHO/i.test(n))return'Takachiho, Miyazaki, Japan';if(/HIMEJI/i.test(n))return'Himeji, Hyogo, Japan';if(/KOBE/i.test(n))return'Kobe, Hyogo, Japan';if(/OSAKA|NAMBA|DOTONBORI|MINAMI/i.test(n))return'Osaka, Japan';if(/KYOTO|ARASHIYAMA|GION|KINKAKU|KIYOMIZU|FUSHIMI/i.test(n))return'Kyoto, Japan';if(/NIKKO/i.test(n))return'Nikko, Tochigi, Japan';if(/KAMAKURA/i.test(n))return'Kamakura, Kanagawa, Japan';return'Tokyo, Japan'}
function active(){if(manual>=0)return manual;const d=DAYS[di];if(!d||d.date!==dateKey())return 0;let x=0,n=jmins();d.stops.forEach((s,i)=>{const m=mins(s.time);if(m!==null&&n>=m)x=i});return x}
function autoDay(){const i=DAYS.findIndex(d=>d.date===dateKey());return i>=0?i:0}
function findFix(reg,name){const n=norm(name);let best=null,bestLen=0;Object.keys(reg||{}).forEach(k=>{const nk=norm(k);if((n===nk||n.includes(nk)||nk.includes(n))&&nk.length>bestLen){best=reg[k];bestLen=nk.length}});return best}
function baseName(name){return String(name||'').replace(/\b(optional|target|exterior|speed lunch|dinner|night|morning atmosphere|friday|saturday|at dawn)\b/ig,'').replace(/[·→]/g,' ').replace(/\s+/g,' ').trim()}
function buildIndex(){placeIndex.length=0;function add(o,d,z){if(!o||!o.name)return;placeIndex.push({n:norm(o.name),o,d,z})}DAYS.forEach(d=>{(d.stops||[]).forEach(o=>add(o,d,null));(ZONES[d.date]||[]).forEach(z=>{(z.sequence||[]).forEach(o=>add(o,d,z));(z.extras||[]).forEach(o=>add(o,d,z));(z.alternates||[]).forEach(o=>add(o,d,z))})})}
function indexedMatch(o,d,z){if(!o||!o.name)return null;const n=norm(o.name);let best=null,score=0;placeIndex.forEach(p=>{if(p.o===o)return;if(d&&p.d&&p.d.date!==d.date)return;let s=0;if(p.n===n)s=1000;else if(p.n.includes(n)||n.includes(p.n))s=Math.min(p.n.length,n.length);else{const a=new Set(n.split(' ').filter(x=>x.length>2)),b=new Set(p.n.split(' ').filter(x=>x.length>2));let common=0;a.forEach(x=>{if(b.has(x))common++});s=common*4}if(s>score&&(coords(p.o)||p.o.mapsQuery)){score=s;best=p}});return score>=8?best:null}
function navInfo(o,d,z){if(!o)return{disabled:true};if(o.nav===false)return{disabled:true,note:o.note||''};if(o.mapsQuery)return{q:o.mapsQuery};const fix=findFix(AUD.NAV||{},o.name);if(fix){if(fix.nav===false)return{disabled:true,note:fix.note||''};return{q:fix.q,note:fix.note||''}}
 const ix=indexedMatch(o,d,z);if(ix){if(ix.o.mapsQuery)return{q:ix.o.mapsQuery};if(coords(ix.o))return{lat:Number(ix.o.lat),lng:Number(ix.o.lng)}}
 if(coords(o)&&!/MOVE|TRAIN|DRIVE|LOGISTICS|RESET|SLEEP|BOOKING/.test(o.type||''))return{lat:Number(o.lat),lng:Number(o.lng)};
 if(/MOVE|TRAIN|DRIVE|LOGISTICS|RESET|SLEEP|BOOKING/.test(o.type||''))return{q:baseName(o.name)+' '+dayContext(d,z)};
 return{q:baseName(o.name)+' '+dayContext(d,z)} }
function resolvedCoords(o,d,z){const ni=navInfo(o,d,z);if(Number.isFinite(ni.lat))return[ni.lat,ni.lng];if(coords(o)&&!ni.q)return[Number(o.lat),Number(o.lng)];const ix=indexedMatch(o,d,z);return ix&&coords(ix.o)?[Number(ix.o.lat),Number(ix.o.lng)]:coords(o)?[Number(o.lat),Number(o.lng)]:null}
function travelMode(o,z){if(/DRIVE/.test(o&&o.type||'')||/driv/i.test(z&&z.mode||''))return'driving';if(/TRAIN|MOVE/.test(o&&o.type||''))return'transit';return'walking'}
function dirUrl(o,d,z){const n=navInfo(o,d,z);if(n.disabled)return'';const dest=n.q?encodeURIComponent(n.q):n.lat+','+n.lng;return'https://www.google.com/maps/dir/?api=1&destination='+dest+'&travelmode='+travelMode(o,z)}
function pinUrl(o,d,z){const n=navInfo(o,d,z);if(n.disabled)return'';const q=n.q?n.q:(Number.isFinite(n.lat)?n.lat+','+n.lng:baseName(o.name)+' '+dayContext(d,z));return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function embedUrl(o,d,z){const n=navInfo(o,d,z);if(n.disabled)return'';const q=n.q?n.q:(Number.isFinite(n.lat)?n.lat+','+n.lng:'');return q?'https://www.google.com/maps?q='+encodeURIComponent(q)+'&z=16&output=embed':''}

// -------- deterministic imagery: exact Wikipedia title -> exact Commons query -> no wrong city fallback --------
function photoTitle(name){return findFix(AUD.PHOTOS||{},name)}
async function wikiTitleImage(title){if(!title)return null;try{const u='https://en.wikipedia.org/w/api.php?action=query&redirects=1&titles='+encodeURIComponent(title)+'&prop=pageimages&piprop=thumbnail|name&pithumbsize=1200&format=json&origin=*';const r=await fetch(u),j=await r.json(),p=j.query&&j.query.pages?Object.values(j.query.pages)[0]:null;if(p&&p.thumbnail&&p.thumbnail.source)return{url:p.thumbnail.source,source:p.title||title}}catch(e){}return null}
async function commonsImages(query){if(!query)return[];try{const u='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=8&gsrsearch='+encodeURIComponent(query)+'&prop=imageinfo&iiprop=url&iiurlwidth=1200&format=json&origin=*';const r=await fetch(u),j=await r.json(),ps=j.query&&j.query.pages?Object.values(j.query.pages):[];return ps.map(p=>({url:p.imageinfo&&p.imageinfo[0]&&(p.imageinfo[0].thumburl||p.imageinfo[0].url),source:p.title||''})).filter(x=>x.url&&/\.(jpg|jpeg|png|webp)(\?|$)/i.test(x.url))}catch(e){return[]}}
async function imageFor(o,d,z){const identity=(photoTitle(o.name)||baseName(o.name)+' '+dayContext(d,z)).trim();if(usedByIdentity.has(identity))return usedByIdentity.get(identity);let result=null;const exact=photoTitle(o.name);if(exact)result=await wikiTitleImage(exact);if(!result){const candidates=await commonsImages(baseName(o.name)+' '+dayContext(d,z));result=candidates.find(c=>!usedImageUrls.has(c.url))||candidates[0]||null}if(result){usedByIdentity.set(identity,result);usedImageUrls.set(result.url,identity)}return result}
function setPhoto(el,o,d,z){if(!el)return;el.classList.add('loading');el.classList.remove('no-photo');el.style.backgroundImage='';el.dataset.label=baseName(o&&o.name||z&&z.name||'Japan');imageFor(o||{name:z.name},d,z).then(r=>{el.classList.remove('loading');if(r){el.style.backgroundImage='url("'+r.url.replace(/"/g,'%22')+'")';el.dataset.source=r.source}else{el.classList.add('no-photo');el.dataset.source=''}})}

function renderRail(){const r=$('#dayRail');r.innerHTML='';DAYS.forEach((d,i)=>{const b=document.createElement('button');b.className='daybtn'+(i===di?' active':'');b.textContent=d.short+' · '+d.city.split(' · ')[0].split(' → ')[0];b.onclick=()=>setDay(i);r.appendChild(b)});setTimeout(()=>r.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'}),20)}
function setDay(i){if(!DAYS[i])return;di=i;manual=-1;try{localStorage.setItem('jp12.day',String(i))}catch(e){}renderAll();panel('today');window.scrollTo({top:0,behavior:'smooth'})}
function renderHead(){const d=DAYS[di],zs=ZONES[d.date]||[];$('#dayDate').textContent='DAY '+(di+1)+' · '+d.short;$('#dayTitle').textContent=d.city;$('#dayMission').textContent=d.mission;$('#sleepMeta').textContent='Sleep: '+d.sleep;$('#stopCountMeta').textContent=d.stops.length+' planned stops';$('#zoneCountMeta').textContent=zs.length+' route areas';const a=$('#dayAlerts');if(a){a.innerHTML=(d.alerts||[]).map(x=>'<article class="dayalert '+(x.level||'info')+'"><b>'+x.title+'</b><p>'+x.text+'</p></article>').join('')}}
function renderStatus(){const d=DAYS[di],i=active(),s=d.stops[i]||d.stops[0],n=d.stops[Math.min(i+1,d.stops.length-1)]||s;$('#nowName').textContent=s.name;$('#nowDesc').textContent=s.desc;$('#nextName').textContent=n.name;$('#nextTime').textContent=(n.time||'')+(n.end?'–'+n.end:'');const a=$('#nextDir'),u=dirUrl(n,d,zoneFor(i+1));if(u){a.href=u;a.hidden=false}else{a.hidden=true}}
function areaPreview(){const d=DAYS[di],r=$('#areaStrip'),zs=ZONES[d.date]||[];r.innerHTML='';zs.forEach((z,i)=>{const a=document.createElement('article');a.className='areamini';a.innerHTML='<div class="imgbox"></div><div class="body"><small>'+z.time+'</small><h3>'+z.name+'</h3><p>'+z.summary+'</p><div class="microstats">'+((z.sequence||[]).length?'<span>'+z.sequence.length+' route points</span>':'')+((z.alternates||[]).length?'<span>'+z.alternates.length+' decisions</span>':'')+'</div><button>Open full area plan</button></div>';setPhoto(a.querySelector('.imgbox'),{name:z.name},d,z);a.querySelector('button').onclick=()=>{panel('areas');setTimeout(()=>$('#area-'+i)?.scrollIntoView({behavior:'smooth',block:'start'}),80)};r.appendChild(a)})}
function timeline(){const d=DAYS[di],r=$('#timeline');r.innerHTML='';d.stops.forEach((s,i)=>{const k=d.date+':'+i,z=zoneFor(i),a=document.createElement('article'),u=dirUrl(s,d,z);a.className='stop'+(i===active()?' current':'');a.innerHTML='<div class="stoptime">'+s.time+'<small>'+(s.end||'')+'</small></div><div class="imgbox stopimg"></div><div class="stopcopy"><h3>'+s.name+'</h3><p>'+s.desc+'</p><div class="stopmeta"><span class="tag '+(s.priority==='MUST'?'must':'')+' '+(s.priority==='BOOK'?'book':'')+'">'+s.priority+'</span><span class="tag">'+s.type+'</span></div><div class="stoptools"><button class="details">Full details</button>'+(u?'<a target="_blank" rel="noopener" href="'+u+'">Directions</a>':'<span class="nolink">Use saved pin</span>')+'<button class="mark '+(done.has(k)?'done':'')+'">'+(done.has(k)?'Done':'Mark done')+'</button></div></div>';setPhoto(a.querySelector('.stopimg'),s,d,z);a.querySelector('.details').onclick=()=>openPlace(s,i);a.querySelector('.mark').onclick=()=>{done.has(k)?done.delete(k):done.add(k);try{localStorage.setItem('jp12.done',JSON.stringify(Array.from(done)))}catch(e){}timeline()};r.appendChild(a)})}
function linkFor(o,d,z,label='Directions ↗'){const u=dirUrl(o,d,z);return u?'<a target="_blank" rel="noopener" href="'+u+'">'+label+'</a>':'<span class="nolink">No fake pin</span>'}
function routeRows(z,d){return(z.sequence||[]).map((x,i)=>'<div class="routepoint"><div class="rnum">'+(i+1)+'</div><div><div class="rtitle"><h4>'+x.name+'</h4><span>'+(x.minutes||'')+'</span></div><p>'+x.note+'</p><div class="rlinks">'+linkFor(x,d,z)+(pinUrl(x,d,z)?'<a target="_blank" rel="noopener" href="'+pinUrl(x,d,z)+'">Open pin ↗</a>':'')+'</div></div></div>').join('')}
function alternateRows(z,d){return(z.alternates||[]).map(x=>'<div class="decision"><span>'+(x.status||'OPTION')+'</span><div><h4>'+x.name+'</h4><p>'+x.note+'</p><div class="rlinks">'+linkFor(x,d,z,'Map / directions ↗')+'</div></div></div>').join('')}
function extraRows(a,d,z){return(a||[]).map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div>'+linkFor(x,d,z,'Map')+'</div>').join('')}
function foodRows(a){return(a||[]).map(x=>'<div class="rowitem"><div><h4>'+x.name+'</h4><p>'+x.note+'</p></div><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((x.q||x.name)+' Japan')+'">Find</a></div>').join('')}
function areas(){const d=DAYS[di],r=$('#areas'),zs=ZONES[d.date]||[];r.innerHTML='';zs.forEach((z,i)=>{const a=document.createElement('article');a.className='area';a.id='area-'+i;const rr=routeRows(z,d),ar=alternateRows(z,d),er=extraRows(z.extras,d,z),fr=foodRows(z.food);a.innerHTML='<div class="imgbox areaimg"></div><div class="areacontent"><small>'+z.time+' · '+(z.mode||'')+'</small><h2>'+z.name+'</h2><p class="areasummary">'+z.summary+'</p>'+(z.strategy?'<div class="expertcall"><b>ROUTE LOGIC</b><p>'+z.strategy+'</p></div>':'')+(rr?'<div class="subsection"><h3>DO THIS IN ORDER</h3>'+rr+'</div>':'')+(ar?'<div class="subsection decisions"><h3>DECISIONS / ALTERNATES</h3>'+ar+'</div>':'')+(z.photo?'<div class="expertcall photo"><b>PHOTO PLAN</b><p>'+z.photo+'</p></div>':'')+(z.cut?'<div class="expertcall cut"><b>IF YOU ARE LATE</b><p>'+z.cut+'</p></div>':'')+(z.rules?'<div class="expertcall rules"><b>IMPORTANT</b><p>'+z.rules+'</p></div>':'')+(er?'<div class="subsection"><h3>EXTRA PINS WORTH KNOWING</h3>'+er+'</div>':'')+(fr?'<div class="subsection"><h3>FOOD THAT FITS THIS ROUTE</h3>'+fr+'</div>':'')+'</div>';setPhoto(a.querySelector('.areaimg'),{name:z.name},d,z);r.appendChild(a)})}
function trip(){const r=$('#tripGrid');r.innerHTML='';DAYS.forEach((d,i)=>{const x=document.createElement('article');x.className='tripday';x.innerHTML='<small>'+d.short+' · DAY '+(i+1)+'</small><h3>'+d.city+'</h3><p>'+d.title+'<br><b>Sleep:</b> '+d.sleep+'</p><button>Open day</button>';x.querySelector('button').onclick=()=>setDay(i);r.appendChild(x)})}
function ensureMap(){if(mapReady)return true;if(!window.L)return false;map=L.map('map',{zoomControl:false});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);mapReady=true;return true}
function clearMap(){layers.forEach(m=>{try{m.remove()}catch(e){}});layers=[];if(routeLine){try{routeLine.remove()}catch(e){}routeLine=null}}
function addMarker(o,d,z,html,style,bounds){const c=resolvedCoords(o,d,z);if(!c)return;bounds.push(c);const ic=L.divIcon({className:'',html:'<div class="'+style+'">'+html+'</div>',iconSize:[28,28],iconAnchor:[14,14]});const u=dirUrl(o,d,z),m=L.marker(c,{icon:ic}).addTo(map).bindPopup('<div class="popup"><b>'+o.name+'</b><p>'+(o.desc||o.note||'')+'</p>'+(u?'<a target="_blank" href="'+u+'">Directions ↗</a>':'')+'</div>');layers.push(m)}
function renderMap(){if(!ensureMap()){toast('Map layer failed. Exact Google Maps buttons still work.');return}clearMap();const d=DAYS[di],zs=ZONES[d.date]||[],bounds=[],route=[];d.stops.forEach((s,i)=>{const c=resolvedCoords(s,d,zoneFor(i));if(c)route.push(c);addMarker(s,d,zoneFor(i),String(i+1),'planpin',bounds)});const seen=new Set(route.map(c=>c.map(v=>v.toFixed(4)).join(',')));zs.forEach(z=>{(z.sequence||[]).forEach(x=>{const c=resolvedCoords(x,d,z);if(!c)return;const k=c.map(v=>v.toFixed(4)).join(',');if(seen.has(k))return;seen.add(k);addMarker(x,d,z,'•',/photo/i.test(x.type||'')?'photopin':'routepin',bounds)});(z.extras||[]).forEach(x=>{const c=resolvedCoords(x,d,z);if(!c)return;const k=c.map(v=>v.toFixed(4)).join(',');if(seen.has(k))return;seen.add(k);addMarker(x,d,z,'+',/skip/i.test(x.type||'')?'skippin':'extrapin',bounds)})});if(route.length>1)routeLine=L.polyline(route,{color:'#0a84ff',weight:3,opacity:.65,dashArray:'7 7'}).addTo(map);if(bounds.length)map.fitBounds(bounds,{padding:[28,28],maxZoom:14});setTimeout(()=>map.invalidateSize(),80)}
function zoneFor(i){const d=DAYS[di],zs=ZONES[d.date]||[],s=d.stops[i];if(!zs.length||!s)return null;const sm=mins(s.time);let z=zs[0],best=-1;zs.forEach(x=>{const m=mins(x.time);if(m!==null&&sm!==null&&m<=sm&&m>best){best=m;z=x}});return z}
function openPlace(s,i){const d=DAYS[di],z=zoneFor(i);$('#drawer').classList.add('open');$('#backdrop').classList.add('open');$('#drawerName').textContent=s.name;$('#drawerMeta').textContent=(s.time||'')+(s.end?'–'+s.end:'')+' · '+s.type+' · '+s.priority;$('#drawerDesc').textContent=s.desc;setPhoto($('#drawerHero'),s,d,z);const du=dirUrl(s,d,z),pu=pinUrl(s,d,z),da=$('#drawerDir'),pa=$('#drawerPin');if(du){da.href=du;da.hidden=false}else da.hidden=true;if(pu){pa.href=pu;pa.hidden=false}else pa.hidden=true;const f=$('#drawerMap'),eu=embedUrl(s,d,z);if(eu){f.src=eu;f.hidden=false}else{f.hidden=true;f.src=''}const seq=z&&z.sequence?(z.sequence||[]).filter(x=>norm(x.name)!==norm(s.name)).slice(0,7):[],ex=z&&z.extras?(z.extras||[]).slice(0,5):[];$('#drawerNearby').innerHTML=extraRows(seq.concat(ex),d,z)||'<p class="empty">No extra stop is worth forcing here.</p>';$('#drawerFood').innerHTML=foodRows(z&&z.food?z.food.slice(0,5):[])||'<p class="empty">Keep moving; use the next food zone.</p>'}
function closeDrawer(){$('#drawer').classList.remove('open');$('#backdrop').classList.remove('open');$('#drawerMap').src=''}
function panel(p){$$('.panel').forEach(x=>x.classList.remove('active'));$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.panel===p));$('#'+p+'Panel').classList.add('active');if(p==='map')setTimeout(renderMap,40);if(p==='areas')areas();window.scrollTo({top:0,behavior:'smooth'})}
function locate(){if(!navigator.geolocation)return toast('Location unavailable');navigator.geolocation.getCurrentPosition(pos=>{const d=DAYS[di],all=[];d.stops.forEach((x,i)=>all.push({x,i,z:zoneFor(i)}));(ZONES[d.date]||[]).forEach(z=>(z.sequence||[]).concat(z.extras||[]).forEach(x=>all.push({x,i:null,z})));let best={dist:1e9};all.forEach(o=>{const c=resolvedCoords(o.x,d,o.z);if(!c)return;const dx=(pos.coords.latitude-c[0])*111,dy=(pos.coords.longitude-c[1])*90,dist=Math.sqrt(dx*dx+dy*dy);if(dist<best.dist)best={...o,dist}});if(!best.x)return toast('Could not match your location to a verified pin');toast('Closest: '+best.x.name+' · '+best.dist.toFixed(1)+' km');if(best.i!==null){manual=best.i;renderStatus();openPlace(best.x,best.i)}else{const u=dirUrl(best.x,d,best.z);if(u)window.open(u,'_blank')}if(mapReady){if(userMarker)userMarker.remove();userMarker=L.circleMarker([pos.coords.latitude,pos.coords.longitude],{radius:8,color:'#fff',weight:3,fillColor:'#34c759',fillOpacity:1}).addTo(map);map.setView([pos.coords.latitude,pos.coords.longitude],15)}},()=>toast('Allow location access when you are in Japan'),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function renderSearch(q){const s=norm(q),out=[];if(s)DAYS.forEach((d,dx)=>{d.stops.forEach((x,si)=>{if(norm(x.name+' '+x.desc+' '+d.city).includes(s))out.push({d,dx,x,si,type:'stop'})});(ZONES[d.date]||[]).forEach(z=>{(z.sequence||[]).concat(z.extras||[]).concat(z.alternates||[]).forEach(x=>{if(norm(x.name+' '+x.note+' '+z.name+' '+d.city).includes(s))out.push({d,dx,x,z,type:'place'})});(z.food||[]).forEach(x=>{if(norm(x.name+' '+x.note+' '+z.name+' '+d.city).includes(s))out.push({d,dx,x,z,type:'food'})})})});const list=out.slice(0,60);$('#searchResults').innerHTML=list.map((o,i)=>'<div class="searchresult" data-i="'+i+'"><b>'+o.x.name+'</b><small>'+o.d.short+' · '+o.d.city+' · '+o.type+'</small></div>').join('');$$('.searchresult').forEach((e,i)=>e.onclick=()=>{const o=list[i];di=o.dx;renderAll();$('#searchOverlay').classList.remove('open');if(o.type==='stop')openPlace(o.x,o.si);else if(o.type==='food')window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((o.x.q||o.x.name)+' Japan'),'_blank');else{const u=dirUrl(o.x,o.d,o.z);if(u)window.open(u,'_blank')}})}
function renderAll(){buildIndex();renderRail();renderHead();renderStatus();areaPreview();timeline();trip();if($('#areasPanel').classList.contains('active'))areas();if(mapReady)renderMap()}
function bind(){$$('.navbtn').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$('#locateBtn').onclick=locate;$('#locateBtn2').onclick=locate;$('#resetNow').onclick=()=>{manual=-1;renderStatus();toast('Following itinerary')};$('#brandBtn').onclick=()=>setDay(autoDay());$('#closeDrawer').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#searchBtn').onclick=()=>{$('#searchOverlay').classList.add('open');setTimeout(()=>$('#searchInput').focus(),40)};$('#closeSearch').onclick=()=>$('#searchOverlay').classList.remove('open');$('#searchInput').oninput=e=>renderSearch(e.target.value)}
function init(){if(!DAYS.length)return;buildIndex();const real=autoDay(),onTrip=DAYS.some(d=>d.date===dateKey()),stored=Number(localStorage.getItem('jp12.day'));di=onTrip?real:(Number.isInteger(stored)&&stored>=0&&stored<DAYS.length?stored:0);bind();renderAll();panel('today')}
document.addEventListener('DOMContentLoaded',init);
})();