(function(){'use strict';
const DATA=window.JAPAN_TRIP;const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));let dayIndex=0,map=null,mapLayer=[],routeLine=null,userMarker=null,manualStop=null;const photoCache=new Map();const usedPhotos=new Set();
function o(a){return{time:a[0],name:a[1],type:a[2],priority:a[3],query:a[4],lat:a[5],lng:a[6],wiki:a[7],desc:a[8]}}
function stops(d){return d.zones.flatMap((z,zi)=>z.stops.map((s,si)=>({...o(s),zi,si}))) }
function lodging(d){return d.sleep?DATA.lodgings[d.sleep]:null}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function jstDate(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return''}}
function jstMin(){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return +p.find(x=>x.type==='hour').value*60 + +p.find(x=>x.type==='minute').value}catch(e){return 0}}
function min(t){const m=String(t||'').match(/(\d{1,2}):(\d{2})/);return m?+m[1]*60 + +m[2]:null}
function currentStopIndex(d){if(manualStop!=null)return manualStop;const all=stops(d);if(d.date!==jstDate())return 0;const now=jstMin();let ix=0;all.forEach((s,i)=>{const m=min(s.time);if(m!==null&&now>=m)ix=i});return ix}
function dirUrl(s){if(!s||!s.query)return'';return'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(s.query)+'&travelmode='+(/TRAIN|MOVE/.test(s.type)?'transit':/DRIVE|ARRIVAL|LOGISTICS/.test(s.type)?'driving':'walking')}
function pinUrl(s){if(!s||!s.query)return'';return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.query)}
function embedUrl(s){if(!s||!s.query)return'';return'https://www.google.com/maps?q='+encodeURIComponent(s.query)+'&z=16&output=embed'}
function homeUrl(d){const l=lodging(d);return l?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(l.address):''}
function exactWiki(title){if(!title)return Promise.resolve(null);if(photoCache.has(title))return photoCache.get(title);const p=fetch('https://en.wikipedia.org/w/api.php?action=query&redirects=1&titles='+encodeURIComponent(title)+'&prop=pageimages&piprop=thumbnail&pithumbsize=1000&format=json&origin=*').then(r=>r.json()).then(j=>{const pages=j.query&&j.query.pages?Object.values(j.query.pages):[];const pg=pages[0];return pg&&pg.thumbnail?{url:pg.thumbnail.source,title:pg.title}:null}).catch(()=>null);photoCache.set(title,p);return p}
function setPhoto(el,title,label,allowRepeat=false){if(!el)return;el.classList.add('fallback');el.dataset.label=label||title||'Japan';el.style.backgroundImage='';if(!title)return;exactWiki(title).then(x=>{if(!x)return;if(!allowRepeat&&usedPhotos.has(x.url))return;usedPhotos.add(x.url);el.style.backgroundImage='url("'+x.url.replace(/"/g,'%22')+'")';el.classList.remove('fallback')})}
function resetPhotos(){usedPhotos.clear()}
function renderRail(){const r=$('#dayRail');r.innerHTML='';DATA.days.forEach((d,i)=>{const b=document.createElement('button');b.className='daybtn'+(i===dayIndex?' active':'');b.textContent=d.label+' · '+d.city.split('→')[0].trim();b.onclick=()=>selectDay(i);r.appendChild(b)});setTimeout(()=>r.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'}),20)}
function renderHead(){const d=DATA.days[dayIndex],l=lodging(d);$('#dayEyebrow').textContent='DAY '+(dayIndex+1)+' · '+d.label;$('#dayTitle').textContent=d.city;$('#dayMission').textContent=d.mission;$('#dayMeta').innerHTML='<span class="pill">'+stops(d).length+' route stops</span><span class="pill">'+d.zones.length+' areas</span>'+(l?'<a class="pill" target="_blank" rel="noopener" href="'+homeUrl(d)+'">Sleep: '+l.name+' ↗</a>':'<span class="pill">Departure</span>')+'<span class="pill">AUDITED '+DATA.audited+'</span>';$('#alerts').innerHTML=(d.alerts||[]).map(a=>'<article class="alert '+(a.k||'')+'"><b>'+a.t+'</b><p>'+a.x+'</p></article>').join('')}
function renderStatus(){const d=DATA.days[dayIndex],all=stops(d),ix=currentStopIndex(d),cur=all[ix]||all[0],next=all[Math.min(ix+1,all.length-1)]||cur;if(!cur)return;$('#currentName').textContent=cur.name;$('#currentDesc').textContent=cur.desc;$('#nextName').textContent=next.name;$('#nextTime').textContent=next.time;const a=$('#nextDir'),u=dirUrl(next);a.hidden=!u;if(u)a.href=u}
function renderZoneStrip(){const d=DATA.days[dayIndex],r=$('#zoneStrip');r.innerHTML='';d.zones.forEach((z,i)=>{const c=document.createElement('article');c.className='zonecard';c.innerHTML='<div class="photo"></div><div class="zonebody"><small>'+z.time+'</small><h3>'+z.name+'</h3><p>'+z.summary+'</p><button class="btn soft">Open area</button></div>';setPhoto(c.querySelector('.photo'),z.image,z.name,true);c.querySelector('button').onclick=()=>{switchPanel('areas');setTimeout(()=>$('#zone-'+i)?.scrollIntoView({behavior:'smooth',block:'start'}),40)};r.appendChild(c)})}
function priorityClass(p){p=String(p||'').toLowerCase();return p==='must'?'must':p==='book'?'book':p==='closed'?'closed':''}
function renderTimeline(){const d=DATA.days[dayIndex],r=$('#timeline'),all=stops(d),curIx=currentStopIndex(d);r.innerHTML='';all.forEach((s,i)=>{const c=document.createElement('article');c.className='stopcard';c.innerHTML='<div class="stime">'+s.time+'</div><div class="photo stopphoto"></div><div class="stopcopy"><h3>'+s.name+'</h3><p>'+s.desc+'</p><div class="tags"><span class="tag '+priorityClass(s.priority)+'">'+s.priority+'</span><span class="tag">'+s.type+'</span>'+(i===curIx?'<span class="tag must">CURRENT</span>':'')+'</div><div class="stoptools"><button class="btn soft details">Details</button>'+(dirUrl(s)?'<a class="btn primary" target="_blank" rel="noopener" href="'+dirUrl(s)+'">Directions</a>':'')+'</div></div>';setPhoto(c.querySelector('.stopphoto'),s.wiki,s.name);c.querySelector('.details').onclick=()=>openDrawer(s,d.zones[s.zi],d);r.appendChild(c)})}
function renderAreas(){const d=DATA.days[dayIndex],r=$('#areas');r.innerHTML='';d.zones.forEach((z,zi)=>{const c=document.createElement('article');c.className='areacard';c.id='zone-'+zi;const rows=z.stops.map((a,i)=>{const s=o(a);return'<div class="rpoint"><div class="rnum">'+(i+1)+'</div><div><h4>'+s.name+'</h4><p>'+s.desc+'</p><div class="rmeta">'+s.time+' · '+s.priority+' · '+s.type+'</div><div class="rlinks">'+(dirUrl(s)?'<a target="_blank" rel="noopener" href="'+dirUrl(s)+'">Directions ↗</a>':'')+(pinUrl(s)?'<a target="_blank" rel="noopener" href="'+pinUrl(s)+'">Open pin ↗</a>':'')+'</div></div></div>'}).join('');const food=(z.food||[]).map(f=>'<div class="foodrow"><div><h4>'+f[0]+'</h4><p>'+f[2]+'</p></div><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(f[1])+'">Find ↗</a></div>').join('');c.innerHTML='<div class="photo hero"></div><div class="areabody"><small>'+z.time+'</small><h2>'+z.name+'</h2><p>'+z.summary+'</p><div class="route"><h3>DO THIS IN ORDER</h3>'+rows+'</div>'+(z.cut?'<div class="callout cut"><b>IF THE CLOCK SLIPS</b><p>'+z.cut+'</p></div>':'')+(food?'<div class="food"><h3>FOOD THAT FITS THE ROUTE</h3>'+food+'</div>':'')+'</div>';setPhoto(c.querySelector('.hero'),z.image,z.name,true);r.appendChild(c)})}
function renderTrip(){const r=$('#tripGrid');r.innerHTML='';DATA.days.forEach((d,i)=>{const l=lodging(d),c=document.createElement('article');c.className='tripcard';c.innerHTML='<small>'+d.label+' · DAY '+(i+1)+'</small><h3>'+d.city+'</h3><p>'+d.mission+(l?'<br><b>Sleep:</b> '+l.address:'')+'</p><button class="btn soft">Open day</button>';c.querySelector('button').onclick=()=>selectDay(i);r.appendChild(c)})}
function ensureMap(){if(map)return true;if(!window.L)return false;map=L.map('map',{zoomControl:false});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);return true}
function clearMap(){mapLayer.forEach(x=>{try{x.remove()}catch(e){}});mapLayer=[];if(routeLine){routeLine.remove();routeLine=null}}
function renderMap(){if(!ensureMap()){toast('Map layer unavailable. Directions buttons still work.');return}clearMap();const d=DATA.days[dayIndex],all=stops(d),pts=[];all.forEach((s,i)=>{if(!Number.isFinite(Number(s.lat))||!Number.isFinite(Number(s.lng)))return;pts.push([+s.lat,+s.lng]);const cls=s.type==='HOME'?'homepin':i===currentStopIndex(d)?'currentpin':'pin';const icon=L.divIcon({className:'',html:'<div class="pin '+cls+'">'+(i+1)+'</div>',iconSize:[28,28],iconAnchor:[14,14]});const m=L.marker([+s.lat,+s.lng],{icon}).addTo(map).bindPopup('<b>'+s.name+'</b><br><small>'+s.time+' · '+s.type+'</small><p style="font-size:11px">'+s.desc+'</p>'+(dirUrl(s)?'<a target="_blank" href="'+dirUrl(s)+'">Google Maps directions ↗</a>':''));mapLayer.push(m)});if(pts.length>1)routeLine=L.polyline(pts,{color:'#0878f9',weight:3,opacity:.55,dashArray:'7 7'}).addTo(map);if(pts.length)map.fitBounds(pts,{padding:[28,28],maxZoom:13});setTimeout(()=>map.invalidateSize(),80)}
function openDrawer(s,z,d){$('#drawer').classList.add('open');$('#drawerBack').classList.add('open');$('#drawerTitle').textContent=s.name;$('#drawerMeta').textContent=s.time+' · '+s.priority+' · '+s.type;$('#drawerDesc').textContent=s.desc;setPhoto($('#drawerPhoto'),s.wiki,s.name,true);const du=dirUrl(s),pu=pinUrl(s);$('#drawerDir').hidden=!du;$('#drawerPin').hidden=!pu;if(du)$('#drawerDir').href=du;if(pu)$('#drawerPin').href=pu;const e=embedUrl(s);$('#drawerMap').hidden=!e;if(e)$('#drawerMap').src=e;const nearby=z.stops.map(o).filter(x=>x.name!==s.name).slice(0,6);$('#drawerNearby').innerHTML=nearby.map(x=>'<div class="nearrow"><b>'+x.name+'</b><p>'+x.desc+'</p>'+(dirUrl(x)?'<a target="_blank" href="'+dirUrl(x)+'">Directions ↗</a>':'')+'</div>').join('')||'<p>No extra stop needed here.</p>';$('#drawerFood').innerHTML=(z.food||[]).map(f=>'<div class="nearrow"><b>'+f[0]+'</b><p>'+f[2]+'</p><a target="_blank" href="https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(f[1])+'">Find on Google Maps ↗</a></div>').join('')||'<p>No dedicated food stop needed in this zone.</p>'}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawerBack').classList.remove('open');$('#drawerMap').src=''}
function switchPanel(p){$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+p+'Panel').classList.add('active');$$('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.panel===p));if(p==='areas')renderAreas();if(p==='map')renderMap();window.scrollTo({top:0,behavior:'smooth'})}
function selectDay(i){dayIndex=i;manualStop=null;try{localStorage.setItem('japan-v2-day',String(i))}catch(e){}resetPhotos();renderAll();switchPanel('today')}
function locate(){if(!navigator.geolocation){toast('Location is not available on this device');return}navigator.geolocation.getCurrentPosition(pos=>{let best=null;DATA.days.forEach((d,di)=>stops(d).forEach((s,si)=>{if(!Number.isFinite(+s.lat)||!Number.isFinite(+s.lng))return;const dx=(pos.coords.latitude-s.lat)*111,dy=(pos.coords.longitude-s.lng)*90,dist=Math.sqrt(dx*dx+dy*dy);if(!best||dist<best.dist)best={d,di,s,si,dist}}));if(!best)return toast('No route pin matched');dayIndex=best.di;manualStop=best.si;resetPhotos();renderAll();toast('Closest route stop: '+best.s.name+' · '+best.dist.toFixed(1)+' km');openDrawer(best.s,best.d.zones[best.s.zi],best.d)},()=>toast('Allow location access to use this feature'),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function search(q){q=String(q||'').toLowerCase().trim();const results=[];if(q)DATA.days.forEach((d,di)=>d.zones.forEach((z,zi)=>z.stops.forEach((a,si)=>{const s=o(a),hay=(s.name+' '+s.desc+' '+s.type+' '+z.name+' '+d.city).toLowerCase();if(hay.includes(q))results.push({d,di,z,zi,s,si})})));$('#searchResults').innerHTML=results.slice(0,60).map((r,i)=>'<div class="searchrow" data-i="'+i+'"><b>'+r.s.name+'</b><small>'+r.d.label+' · '+r.d.city+' · '+r.z.name+'</small></div>').join('');$$('.searchrow').forEach((el,i)=>el.onclick=()=>{const r=results[i];dayIndex=r.di;resetPhotos();renderAll();$('#search').classList.remove('open');openDrawer({...r.s,zi:r.zi},r.z,r.d)})}
function renderAll(){renderRail();renderHead();renderStatus();renderZoneStrip();renderTimeline();renderTrip();if($('#areasPanel').classList.contains('active'))renderAreas();if($('#mapPanel').classList.contains('active'))renderMap()}
function bind(){$$('.navbtn').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));$('#searchBtn').onclick=()=>{$('#search').classList.add('open');setTimeout(()=>$('#searchInput').focus(),30)};$('#closeSearch').onclick=()=>$('#search').classList.remove('open');$('#searchInput').oninput=e=>search(e.target.value);$('#drawerClose').onclick=closeDrawer;$('#drawerBack').onclick=closeDrawer;$('#locateBtn').onclick=locate;$('#locateBtn2').onclick=locate;$('#followBtn').onclick=()=>{manualStop=null;renderStatus();toast('Following the itinerary again')}}
function init(){const today=DATA.days.findIndex(d=>d.date===jstDate()),stored=Number(localStorage.getItem('japan-v2-day'));dayIndex=today>=0?today:(Number.isInteger(stored)&&stored>=0&&stored<DATA.days.length?stored:0);bind();resetPhotos();renderAll();switchPanel('today')}
document.addEventListener('DOMContentLoaded',init);
})();