(function(){
'use strict';
const T=window.JAPAN_TRIP;if(!T)return;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const stopObj=a=>({time:a[0],name:a[1],type:a[2],priority:a[3],query:a[4],lat:a[5],lng:a[6],wiki:a[7],desc:a[8]});
let journalDB=null,enhancing=false;
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function activeDay(){const b=$('.daybtn.active');if(!b)return T.days[0];const label=(b.textContent||'').split('·')[0].trim();return T.days.find(d=>d.label===label)||T.days[0];}
function exactDest(s){return Number.isFinite(+s.lat)&&Number.isFinite(+s.lng)?(+s.lat)+','+(+s.lng):(s.query||s.name);}
function modeFor(type){type=String(type||'');if(/TRAIN/.test(type))return'transit';if(/DRIVE|ARRIVAL|LOGISTICS/.test(type))return'driving';return'walking';}
function dirUrl(s){const dest=exactDest(s);return dest?'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest)+'&travelmode='+modeFor(s.type):'';}
function pinUrl(s){const q=exactDest(s);return q?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q):'';}
function routeUrl(zone){const ss=zone.stops.map(stopObj).filter(s=>exactDest(s));if(ss.length<2)return'';const first=ss[0],last=ss[ss.length-1],mid=ss.slice(1,-1).slice(0,8);let mode='walking';if(ss.some(s=>/DRIVE|ARRIVAL|LOGISTICS/.test(s.type)))mode='driving';else if(ss.some(s=>/TRAIN/.test(s.type)))mode='transit';return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(exactDest(first))+'&destination='+encodeURIComponent(exactDest(last))+(mid.length?'&waypoints='+encodeURIComponent(mid.map(exactDest).join('|')):'')+'&travelmode='+mode;}
function findStop(d,name){for(const z of d.zones){for(const a of z.stops){if(a[1]===name)return stopObj(a)}}return null;}
function fileUrl(file){return'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent(file)+'?width=1600';}
function photoFor(label){const n=norm(label),P=T.curatedPhotos||{};if(/takachiho|manai|three bridges/.test(n))return P.takachiho;if(/himeji/.test(n))return P.himeji;if(/arashiyama|bamboo/.test(n))return P.arashiyama;if(/shibuya/.test(n))return P.shibuya;if(/kusasenri|aso rim|volcanic core/.test(n))return P.kusasenri;if(/kamakura|great buddha|kotoku/.test(n))return P.kamakura;if(/nikko|toshogu/.test(n))return P.nikko;if(/dotonbori|osaka minami/.test(n))return P.dotonbori;if(/inasa|sunset.*mt/.test(n))return P.inasa;if(/kiyomizu/.test(n))return P.kiyomizu;return null;}
function applyCurated(el,label){const p=photoFor(label);if(!el||!p)return;el.style.backgroundImage='url("'+fileUrl(p.file).replace(/"/g,'%22')+'")';el.classList.remove('fallback');el.dataset.credit=p.credit+' · '+p.license;el.dataset.source=p.source;if(!el.querySelector('.photo-credit')){const a=document.createElement('a');a.className='photo-credit';a.href=p.source;a.target='_blank';a.rel='noopener';a.textContent='Photo: '+p.credit;a.title=p.license+' · Wikimedia Commons';el.appendChild(a);}}
function enhancePhotos(){$$('.zonecard').forEach(c=>applyCurated(c.querySelector('.photo'),c.querySelector('h3')?.textContent));$$('.areacard').forEach(c=>applyCurated(c.querySelector('.hero'),c.querySelector('h2')?.textContent));$$('.stopcard').forEach(c=>applyCurated(c.querySelector('.stopphoto'),c.querySelector('h3')?.textContent));if($('#drawer')?.classList.contains('open'))applyCurated($('#drawerPhoto'),$('#drawerTitle')?.textContent);}
function enhanceLinks(){const d=activeDay();const next=findStop(d,$('#nextName')?.textContent);if(next&&$('#nextDir'))$('#nextDir').href=dirUrl(next);$$('.stopcard').forEach(c=>{const name=c.querySelector('h3')?.textContent,s=findStop(d,name);if(!s)return;c.querySelectorAll('a.btn').forEach(a=>{if(/Directions/i.test(a.textContent))a.href=dirUrl(s)});});$$('.rpoint').forEach(r=>{const s=findStop(d,r.querySelector('h4')?.textContent);if(!s)return;r.querySelectorAll('a').forEach(a=>{if(/Directions/i.test(a.textContent))a.href=dirUrl(s);if(/Open pin/i.test(a.textContent))a.href=pinUrl(s)});});if($('#drawer')?.classList.contains('open')){const s=findStop(d,$('#drawerTitle')?.textContent);if(s){if($('#drawerDir'))$('#drawerDir').href=dirUrl(s);if($('#drawerPin'))$('#drawerPin').href=pinUrl(s)}}$$('.leaflet-popup-content').forEach(p=>{const s=findStop(d,p.querySelector('b')?.textContent),a=p.querySelector('a');if(s&&a&&/Google Maps directions/i.test(a.textContent))a.href=dirUrl(s)});}
function addOfficial(){const d=activeDay(),meta=$('#dayMeta');if(!meta)return;meta.querySelectorAll('.official-pill').forEach(x=>x.remove());(d.officialChecks||[]).forEach(([name,url])=>{const a=document.createElement('a');a.className='pill official-pill';a.href=url;a.target='_blank';a.rel='noopener';a.textContent='Official: '+name+' ↗';meta.appendChild(a)});}
function addRouteButtons(){const d=activeDay();$$('.zonecard').forEach((c,i)=>{if(c.querySelector('.route-direct'))return;const z=d.zones[i],u=z&&routeUrl(z);if(!u)return;const body=c.querySelector('.zonebody'),row=document.createElement('div');row.className='zone-actions';const a=document.createElement('a');a.className='btn dark route-direct';a.href=u;a.target='_blank';a.rel='noopener';a.textContent='Route ↗';row.appendChild(a);body?.appendChild(row)});$$('.areacard').forEach((c,i)=>{if(c.querySelector('.area-route'))return;const z=d.zones[i],u=z&&routeUrl(z);if(!u)return;const body=c.querySelector('.areabody'),a=document.createElement('a');a.className='btn dark area-route';a.href=u;a.target='_blank';a.rel='noopener';a.textContent='Open this area route in Google Maps ↗';body?.insertBefore(a,body.querySelector('.route'))});}
function fixMapNote(){const n=$('.mapnote');if(n)n.textContent='Pins use audited coordinates when available. The line shows visit order, not turn-by-turn streets. Tap Directions for Google Maps navigation; place-name search is used only where a micro-stop has no trustworthy coordinate.';}
function enhanceAll(){if(enhancing)return;enhancing=true;try{enhanceLinks();addOfficial();addRouteButtons();enhancePhotos();fixMapNote();renderJournalHeader();}finally{enhancing=false}}
function openDB(){return new Promise((resolve,reject)=>{if(journalDB)return resolve(journalDB);if(!window.indexedDB)return reject(new Error('IndexedDB unavailable'));const r=indexedDB.open('japan-trip-journal-v23',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('media')){const s=db.createObjectStore('media',{keyPath:'id'});s.createIndex('day','day',{unique:false});}};r.onsuccess=()=>{journalDB=r.result;resolve(journalDB)};r.onerror=()=>reject(r.error)});}
async function saveFiles(files,caption){const d=activeDay(),db=await openDB(),tx=db.transaction('media','readwrite'),store=tx.objectStore('media');for(const f of files)store.put({id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),day:d.date,caption:caption||'',name:f.name,type:f.type,createdAt:Date.now(),blob:f});return new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});}
async function listFiles(){const d=activeDay(),db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('media','readonly'),idx=tx.objectStore('media').index('day'),r=idx.getAll(d.date);r.onsuccess=()=>res((r.result||[]).sort((a,b)=>b.createdAt-a.createdAt));r.onerror=()=>rej(r.error)});}
async function deleteFile(id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});}
function renderJournalHeader(){const d=activeDay();if($('#journalDay'))$('#journalDay').textContent=d.label+' · '+d.city;}
async function renderJournal(){const g=$('#journalGallery');if(!g)return;renderJournalHeader();try{const items=await listFiles();g.innerHTML='';if(!items.length){g.innerHTML='<div class="journal-empty"><b>No media saved for this day yet.</b><p>Add Fuji imports, phone photos or clips. They stay only on this device/browser.</p></div>';return;}items.forEach(it=>{const card=document.createElement('article');card.className='media-card';const url=URL.createObjectURL(it.blob);const media=(it.type||'').startsWith('video/')?'<video src="'+url+'" controls playsinline></video>':'<img src="'+url+'" alt="'+(it.caption||it.name).replace(/"/g,'&quot;')+'">';card.innerHTML=media+'<div class="media-copy"><b>'+(it.caption||it.name)+'</b><small>'+new Date(it.createdAt).toLocaleString()+'</small><button class="media-delete">Remove</button></div>';card.querySelector('.media-delete').onclick=async()=>{await deleteFile(it.id);URL.revokeObjectURL(url);renderJournal()};g.appendChild(card)});}catch(e){g.innerHTML='<div class="journal-empty"><b>Journal unavailable in this browser.</b><p>'+String(e.message||e)+'</p></div>';}}
function bindJournal(){const input=$('#mediaInput'),caption=$('#mediaCaption');if(input)input.onchange=async e=>{const fs=Array.from(e.target.files||[]);if(!fs.length)return;try{await saveFiles(fs,caption?.value||'');e.target.value='';if(caption)caption.value='';renderJournal();toast2('Saved to this device')}catch(err){toast2('Could not save media')}};$$('.navbtn[data-panel="journal"]').forEach(b=>b.addEventListener('click',()=>setTimeout(renderJournal,30)));}
function toast2(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=23').catch(()=>{});}
function init(){enhanceAll();bindJournal();registerSW();const obs=new MutationObserver(()=>{clearTimeout(window.__v23enh);window.__v23enh=setTimeout(enhanceAll,20)});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('.daybtn'))setTimeout(()=>{enhanceAll();if($('#journalPanel')?.classList.contains('active'))renderJournal()},40);if(e.target.closest('.details'))setTimeout(enhanceAll,40)});}
document.addEventListener('DOMContentLoaded',init);
})();