(function(){'use strict';
const T=window.JAPAN_TRIP,P=window.JAPAN_PHOTOS,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));if(!T||!P)return;
let dayIndex=0,liveIndex=0,map=null,mapLayers=[],routeLine=null,journalDB=null;const completeKey='japan-flow-complete-v3';const liveKey='japan-flow-index-v3';
const stopObj=(a,zi,si,gi,z)=>({time:a[0],name:a[1],type:a[2],priority:a[3],query:a[4],lat:a[5],lng:a[6],wiki:a[7],desc:a[8],zi,si,gi,zone:z.name,zoneSummary:z.summary,zoneCut:z.cut});
function flat(d){let g=0;return d.zones.flatMap((z,zi)=>z.stops.map((a,si)=>stopObj(a,zi,si,g++,z)))}
function day(){return T.days[dayIndex]} function all(){return flat(day())}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function jstDate(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return''}}
function jstMin(){try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return +p.find(x=>x.type==='hour').value*60 + +p.find(x=>x.type==='minute').value}catch(e){return 0}}
function mins(t){const m=String(t||'').match(/(\d{1,2}):(\d{2})/);return m?+m[1]*60 + +m[2]:null}
function timeIndex(d){const s=flat(d);if(d.date!==jstDate())return 0;const n=jstMin();let ix=0;s.forEach((x,i)=>{const m=mins(x.time);if(m!==null&&n>=m)ix=i});return ix}
function getProgress(){try{return JSON.parse(localStorage.getItem(completeKey)||'{}')}catch(e){return{}}}
function setProgress(o){try{localStorage.setItem(completeKey,JSON.stringify(o))}catch(e){}}
function sid(d,s){return d.date+'|'+s.zi+'|'+s.si}
function done(s){return !!getProgress()[sid(day(),s)]}
function toggleDone(s,val){const o=getProgress();o[sid(day(),s)]=val==null?!o[sid(day(),s)]:!!val;setProgress(o)}
function savedIndex(d){try{const o=JSON.parse(localStorage.getItem(liveKey)||'{}');return Number.isInteger(o[d.date])?o[d.date]:null}catch(e){return null}}
function saveIndex(){try{const o=JSON.parse(localStorage.getItem(liveKey)||'{}');o[day().date]=liveIndex;localStorage.setItem(liveKey,JSON.stringify(o))}catch(e){}}
function photoKey(text,d=day()){return P.keyFor(text,d.date)}
function photoData(text,d=day()){const k=photoKey(text,d),inf=P.info(k);return{k,url:P.url(k,1800),small:P.url(k,700),source:P.source(k),credit:inf.credit,license:inf.license}}
function bgStyle(text,d=day()){return'background-image:url("'+photoData(text,d).url.replace(/"/g,'%22')+'")'}
function dest(s){return Number.isFinite(+s.lat)&&Number.isFinite(+s.lng)?(+s.lat)+','+(+s.lng):(s.query||s.name)}
function travel(s){return/DRIVE|ARRIVAL|LOGISTICS/.test(s.type)?'driving':/TRAIN|MOVE/.test(s.type)?'transit':'walking'}
function dir(s){return'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest(s))+'&travelmode='+travel(s)}
function pin(s){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(dest(s))}
function routeUrl(z){const ss=z.stops.map((a,i)=>stopObj(a,0,i,i,z)).filter(s=>dest(s));if(ss.length<2)return'';const wp=ss.slice(1,-1).slice(0,8);let mode=ss.some(s=>/DRIVE|ARRIVAL|LOGISTICS/.test(s.type))?'driving':ss.some(s=>/TRAIN/.test(s.type))?'transit':'walking';return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(dest(ss[0]))+'&destination='+encodeURIComponent(dest(ss.at(-1)))+(wp.length?'&waypoints='+encodeURIComponent(wp.map(dest).join('|')):'')+'&travelmode='+mode}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function renderDays(){const r=$('#dayStrip');r.innerHTML='';T.days.forEach((d,i)=>{const b=document.createElement('button');b.className='day-chip'+(i===dayIndex?' active':'');b.textContent=d.label+' · '+d.city.split('→')[0].trim();b.onclick=()=>selectDay(i);r.appendChild(b)});setTimeout(()=>r.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'}),30)}
function completedCount(){return all().filter(done).length}
function renderLive(){const d=day(),ss=all();liveIndex=Math.max(0,Math.min(liveIndex,ss.length-1));const cur=ss[liveIndex]||ss[0],next=ss[Math.min(liveIndex+1,ss.length-1)]||cur,hero=photoData(d.city+' '+cur.zone,d),cp=completedCount(),pct=ss.length?Math.round(cp/ss.length*100):0;$('#liveContent').innerHTML=`<section class="hero"><div class="hero-media" style="${bgStyle(d.city,d)}"></div><a class="hero-credit" href="${hero.source}" target="_blank" rel="noopener">Photo: ${esc(hero.credit)} · ${esc(hero.license)}</a><div class="hero-content"><div class="kicker"><span>${esc(d.label)}</span><span>DAY ${dayIndex+1}</span><span>${ss.length} STOPS</span></div><h1>${esc(d.city)}</h1><p>${esc(d.mission)}</p></div></section><div class="live-wrap"><article class="progress-card"><div class="progress-top"><div><b>${cp}/${ss.length} complete</b><span> · ${pct}% of the day</span></div><span>${esc(cur.zone)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></article><div class="live-grid"><article class="now-card"><div class="now-photo" style="${bgStyle(cur.name+' '+cur.zone,d)}"><span class="now-badge">${done(cur)?'DONE':'YOU ARE HERE'}</span></div><div class="now-body"><div class="now-meta">${esc(cur.time)} · ${esc(cur.priority)} · ${esc(cur.type)}</div><h2>${esc(cur.name)}</h2><p>${esc(cur.desc)}</p><div class="live-actions"><a class="action primary" href="${dir(cur)}" target="_blank" rel="noopener">GO NOW ↗</a><button class="action secondary details-now">Details</button></div><div class="nav-stepper"><button class="stepbtn prev">← Previous</button><button class="stepbtn done">${done(cur)?'Undo done':'✓ Mark done'}</button><button class="stepbtn next">Next →</button></div></div></article><article class="next-card"><div><div class="mini">UP NEXT · ${esc(next.time)}</div><h3>${esc(next.name)}</h3><p>${esc(next.desc)}</p></div><div class="next-thumb" style="${bgStyle(next.name+' '+next.zone,d)}"></div></article></div>${renderAlerts(d)}${renderZoneGlance(d)}</div>`;$('.prev').onclick=()=>move(-1);$('.next').onclick=()=>move(1);$('.done').onclick=()=>{toggleDone(cur);if(done(cur)&&liveIndex<ss.length-1)liveIndex++;saveIndex();renderAll();toast(done(cur)?'Marked complete':'Updated')};$('.details-now').onclick=()=>openSheet(cur);}
function renderAlerts(d){if(!d.alerts?.length)return'';return'<div class="alert-stack">'+d.alerts.slice(0,4).map(a=>`<article class="alert-card"><b>${esc(a.t)}</b><p>${esc(a.x)}</p></article>`).join('')+'</div>'}
function renderZoneGlance(d){return`<article class="zone-glance"><h3>Today by area</h3><div class="zone-row">${d.zones.map((z,i)=>`<button class="zone-pill" data-zone="${i}"><b>${esc(z.name)}</b><span>${esc(z.time)}</span></button>`).join('')}</div></article>`}
function move(delta){const ss=all();liveIndex=Math.max(0,Math.min(ss.length-1,liveIndex+delta));saveIndex();renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function renderFlow(){const d=day();$('#flowTitle').textContent=d.city;$('#flowMission').textContent=d.mission;$('#flowZones').innerHTML=d.zones.map((z,zi)=>{let offset=d.zones.slice(0,zi).reduce((n,x)=>n+x.stops.length,0);return`<section class="flow-zone"><div class="flow-zone-head"><div><a class="flow-zone-route" href="${routeUrl(z)}" target="_blank" rel="noopener">OPEN AREA ROUTE ↗</a><h2>${esc(z.name)}</h2><p>${esc(z.summary)}</p></div><span class="flow-zone-route">${esc(z.time)}</span></div><div class="stop-list">${z.stops.map((a,si)=>{const s=stopObj(a,zi,si,offset+si,z),pd=photoData(s.name+' '+z.name,d);return`<article class="flow-stop ${done(s)?'complete':''}" data-gi="${s.gi}"><div class="flow-thumb" style="background-image:url('${pd.small.replace(/'/g,'%27')}')"></div><div class="flow-copy"><small>${esc(s.time)} · ${esc(s.priority)}</small><h3>${esc(s.name)}</h3><p>${esc(s.desc)}</p></div><button class="flow-check" aria-label="Toggle complete">${done(s)?'✓':'○'}</button></article>`}).join('')}</div>${z.cut?`<div class="alert-card" style="margin-top:10px"><b>IF YOU'RE LATE</b><p>${esc(z.cut)}</p></div>`:''}</section>`}).join('');$$('.flow-stop').forEach(el=>{const s=all()[+el.dataset.gi];el.onclick=e=>{if(e.target.closest('.flow-check')){toggleDone(s);renderFlow();renderLive();return}liveIndex=s.gi;saveIndex();openSheet(s)}})}
function renderTrip(){const r=$('#tripDays');r.innerHTML=T.days.map((d,i)=>{const pd=photoData(d.city,d);return`<button class="trip-day" data-i="${i}" style="background-image:url('${pd.small.replace(/'/g,'%27')}')"><div class="trip-day-copy"><small>${esc(d.label)} · DAY ${i+1}</small><h3>${esc(d.city)}</h3></div></button>`}).join('');$$('.trip-day').forEach(b=>b.onclick=()=>{selectDay(+b.dataset.i);switchView('live')})}
function ensureMap(){if(map||!window.L)return!!map;if(!$('#map'))return false;map=L.map('map',{zoomControl:false,attributionControl:true});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);return true}
function renderMap(){const d=day();$('#mapTitle').textContent=d.city;if(!ensureMap()){toast('Map unavailable');return}mapLayers.forEach(x=>x.remove());mapLayers=[];if(routeLine){routeLine.remove();routeLine=null}const pts=[];all().forEach((s,i)=>{if(!Number.isFinite(+s.lat)||!Number.isFinite(+s.lng))return;pts.push([+s.lat,+s.lng]);const cls=done(s)?'done':i===liveIndex?'now':'';const icon=L.divIcon({className:'',html:`<div class="marker-dot ${cls}">${i+1}</div>`,iconSize:[30,30],iconAnchor:[15,15]});const m=L.marker([+s.lat,+s.lng],{icon}).addTo(map);m.on('click',()=>{liveIndex=i;saveIndex();renderMapSheet(s)});mapLayers.push(m)});if(pts.length>1)routeLine=L.polyline(pts,{color:'#f4d35e',weight:3,opacity:.75,dashArray:'5 7'}).addTo(map);if(pts.length)map.fitBounds(pts,{padding:[28,28],maxZoom:13});setTimeout(()=>map.invalidateSize(),60)}
function renderMapSheet(s){$('#mapSheet').innerHTML=`<div class="map-sheet-card"><span>${esc(s.time)} · ${esc(s.zone)}</span><b>${esc(s.name)}</b><div class="live-actions"><a class="action primary" href="${dir(s)}" target="_blank" rel="noopener">Directions ↗</a><button class="action secondary map-details">Details</button></div></div>`;$('.map-details').onclick=()=>openSheet(s)}
function fitRoute(){if(!map)return;const pts=all().filter(s=>Number.isFinite(+s.lat)&&Number.isFinite(+s.lng)).map(s=>[+s.lat,+s.lng]);if(pts.length)map.fitBounds(pts,{padding:[28,28],maxZoom:13})}
function openSheet(s){const d=day(),pd=photoData(s.name+' '+s.zone,d),z=d.zones[s.zi],n=all()[Math.min(s.gi+1,all().length-1)];$('#sheetContent').innerHTML=`<div class="sheet-hero" style="background-image:url('${pd.url.replace(/'/g,'%27')}')"></div><div class="sheet-body"><small>${esc(s.time)} · ${esc(s.priority)} · ${esc(s.type)}</small><h2>${esc(s.name)}</h2><p>${esc(s.desc)}</p><div class="live-actions"><a class="action primary" href="${dir(s)}" target="_blank" rel="noopener">Directions ↗</a><a class="action secondary" href="${pin(s)}" target="_blank" rel="noopener">Open pin ↗</a></div><button class="action secondary sheet-done" style="width:100%;margin-top:8px">${done(s)?'Undo completed':'✓ Mark completed'}</button><article class="alert-card" style="margin-top:12px"><b>THIS AREA</b><p>${esc(z.summary)}</p></article>${z.cut?`<article class="alert-card" style="margin-top:8px"><b>IF THE CLOCK SLIPS</b><p>${esc(z.cut)}</p></article>`:''}${n&&n!==s?`<article class="alert-card" style="margin-top:8px"><b>NEXT · ${esc(n.time)}</b><p>${esc(n.name)} — ${esc(n.desc)}</p></article>`:''}<p style="font-size:8px;color:#707985;margin-top:12px">Photo: <a href="${pd.source}" target="_blank" rel="noopener" style="color:#9fb7ff">${esc(pd.credit)} · ${esc(pd.license)}</a></p></div>`;$('#stopSheet').classList.add('open');$('#sheetBack').classList.add('open');$('.sheet-done').onclick=()=>{toggleDone(s);renderAll();openSheet(s)}}
function closeSheet(){$('#stopSheet').classList.remove('open');$('#sheetBack').classList.remove('open')}
function switchView(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$$('.dockbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='flow')renderFlow();if(v==='map')renderMap();if(v==='trip')renderTrip();if(v==='journal')renderJournal();window.scrollTo({top:0,behavior:'smooth'})}
function selectDay(i){dayIndex=i;const d=day(),saved=savedIndex(d);liveIndex=saved!=null?saved:timeIndex(d);try{localStorage.setItem('japan-flow-day-v3',String(i))}catch(e){}renderAll();switchView('live')}
function renderAll(){renderDays();renderLive();if($('#flowView').classList.contains('active'))renderFlow();if($('#mapView').classList.contains('active'))renderMap();if($('#tripView').classList.contains('active'))renderTrip();if($('#journalView').classList.contains('active'))renderJournal();bindZoneGlance()}
function bindZoneGlance(){$$('.zone-pill').forEach(b=>b.onclick=()=>{const zi=+b.dataset.zone;liveIndex=day().zones.slice(0,zi).reduce((n,z)=>n+z.stops.length,0);saveIndex();renderAll()})}
function jumpNow(){const i=T.days.findIndex(d=>d.date===jstDate());if(i>=0){dayIndex=i;liveIndex=timeIndex(T.days[i]);saveIndex();renderAll();switchView('live');toast('Jumped to what should be happening now')}else{switchView('live');toast('Trip is not in progress yet')}}
function search(q){q=String(q||'').trim().toLowerCase();const out=[];if(q)T.days.forEach((d,di)=>d.zones.forEach((z,zi)=>{z.stops.forEach((a,si)=>{const s=stopObj(a,zi,si,0,z),hay=(s.name+' '+s.desc+' '+s.type+' '+z.name+' '+d.city).toLowerCase();if(hay.includes(q))out.push({d,di,z,s})});(z.food||[]).forEach(f=>{if((f.join(' ')+' '+z.name+' '+d.city).toLowerCase().includes(q))out.push({d,di,z,food:f})})}));$('#searchResults').innerHTML=out.slice(0,60).map((x,i)=>x.food?`<div class="search-item" data-i="${i}"><b>${esc(x.food[0])}</b><small>${esc(x.d.label)} · FOOD · ${esc(x.z.name)}</small></div>`:`<div class="search-item" data-i="${i}"><b>${esc(x.s.name)}</b><small>${esc(x.d.label)} · ${esc(x.z.name)}</small></div>`).join('');$$('.search-item').forEach((el,i)=>el.onclick=()=>{const x=out[i];dayIndex=x.di;if(x.food){window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.food[1]),'_blank');return}const ss=flat(x.d),idx=ss.findIndex(s=>s.name===x.s.name);liveIndex=Math.max(0,idx);saveIndex();renderAll();$('#searchLayer').classList.remove('open');openSheet(ss[liveIndex])})}
function openDB(){return new Promise((res,rej)=>{if(journalDB)return res(journalDB);const r=indexedDB.open('japan-flow-journal-v3',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('media')){const s=db.createObjectStore('media',{keyPath:'id'});s.createIndex('day','day')}};r.onsuccess=()=>{journalDB=r.result;res(journalDB)};r.onerror=()=>rej(r.error)})}
async function saveMedia(files,caption){const db=await openDB(),tx=db.transaction('media','readwrite'),st=tx.objectStore('media');for(const f of files)st.put({id:(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()),day:day().date,caption:caption||'',name:f.name,type:f.type,created:Date.now(),blob:f});return new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getMedia(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('media','readonly'),r=tx.objectStore('media').index('day').getAll(day().date);r.onsuccess=()=>res((r.result||[]).sort((a,b)=>b.created-a.created));r.onerror=()=>rej(r.error)})}
async function renderJournal(){if(!$('#journalGallery'))return;$('#journalTitle').textContent=day().label+' · '+day().city;const g=$('#journalGallery');try{const items=await getMedia();g.innerHTML=items.length?items.map(x=>{const u=URL.createObjectURL(x.blob);return`<article class="journal-item">${String(x.type).startsWith('video/')?`<video src="${u}" controls playsinline></video>`:`<img src="${u}" alt="${esc(x.caption||x.name)}">`}<div class="journal-copy"><b>${esc(x.caption||x.name)}</b><small>${new Date(x.created).toLocaleString()}</small></div></article>`}).join(''):'<article class="alert-card" style="grid-column:1/-1"><b>No media saved for this day yet.</b><p>Add Fuji imports or phone photos above. They stay only in this browser.</p></article>'}catch(e){g.innerHTML='<article class="alert-card" style="grid-column:1/-1"><b>Journal unavailable.</b><p>This browser may have storage disabled.</p></article>'}}
function bind(){$$('.dockbtn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#jumpNow').onclick=jumpNow;$('#homeBtn').onclick=()=>switchView('live');$('#fitRoute').onclick=fitRoute;$('#sheetClose').onclick=closeSheet;$('#sheetBack').onclick=closeSheet;$('#searchBtn').onclick=()=>{$('#searchLayer').classList.add('open');setTimeout(()=>$('#searchInput').focus(),30)};$('#searchClose').onclick=()=>$('#searchLayer').classList.remove('open');$('#searchInput').oninput=e=>search(e.target.value);$('#journalInput').onchange=async e=>{const files=Array.from(e.target.files||[]);if(!files.length)return;try{await saveMedia(files,$('#journalCaption').value);e.target.value='';$('#journalCaption').value='';renderJournal();toast('Saved to this device')}catch(err){toast('Could not save media')}}}
function init(){const today=T.days.findIndex(d=>d.date===jstDate()),stored=Number(localStorage.getItem('japan-flow-day-v3'));dayIndex=today>=0?today:(Number.isInteger(stored)&&stored>=0&&stored<T.days.length?stored:0);const d=day(),saved=savedIndex(d);liveIndex=saved!=null?saved:timeIndex(d);bind();renderAll();switchView('live')}
document.addEventListener('DOMContentLoaded',init);
})();