(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let observer=null,fieldBar=null,lastFocusName='';
function ensureFieldBar(){if(fieldBar)return fieldBar;fieldBar=document.createElement('div');fieldBar.className='fieldBar';fieldBar.id='fieldBar';fieldBar.innerHTML='<div class="fieldBarText"><small>CURRENT STOP</small><b>Loading…</b></div><a target="_blank" rel="noopener">Directions ↗</a>';document.body.appendChild(fieldBar);return fieldBar}
function currentVisible(){return $('#todayView')?.classList.contains('active')}
function syncFieldBar(){const bar=ensureFieldBar(),card=$('.focusCard'),name=$('.focusBody h2')?.textContent?.trim(),go=$('.focusBody .go');if(!currentVisible()||!card||!name||!go){bar.classList.remove('show');return}bar.querySelector('b').textContent=name;bar.querySelector('a').href=go.href;lastFocusName=name;const r=card.getBoundingClientRect();const should=r.bottom<120||r.top>window.innerHeight;bar.classList.toggle('show',should)}
function imageState(img){if(!img||img.dataset.audited==='1')return;img.dataset.audited='1';const shell=img.closest('.visual');const good=()=>{if(!shell)return;img.classList.add('loaded');img.classList.remove('failed');shell.classList.add('image-ok');shell.classList.remove('failed')};const bad=()=>{if(!shell)return;img.classList.remove('loaded');img.classList.add('failed');shell.classList.add('failed');shell.classList.remove('image-ok');img.style.display='none';const fb=$('.visual-fallback',shell);if(fb){fb.setAttribute('role','img');fb.setAttribute('aria-label',img.alt?`Image unavailable. ${img.alt}`:'Image unavailable')}};if(img.complete){img.naturalWidth>20?good():bad()}else{img.addEventListener('load',good,{once:true});img.addEventListener('error',bad,{once:true});setTimeout(()=>{if(!img.classList.contains('loaded')&&(!img.complete||img.naturalWidth<20))bad()},4500)}}
function auditImages(){$$('.visual-img').forEach(imageState)}
function tightenFallbacks(){ $$('.visual.failed').forEach(v=>{const fb=$('.visual-fallback',v);if(fb&&!fb.querySelector('.fallback-note')){const n=document.createElement('small');n.className='fallback-note';n.textContent='Photo unavailable · route info still works';n.style.cssText='margin-top:6px;font-size:8px;opacity:.7;font-weight:800';fb.appendChild(n)}})}
function enhanceAlerts(){$$('.alertsBox').forEach(x=>{if(!x.dataset.audited){x.dataset.audited='1';x.open=false}})}
function makeRouteUseful(){const page=$('#routeView .routePage');if(!page||page.dataset.audited)return;page.dataset.audited='1';const title=$('.pageTitle',page);if(title){const hint=document.createElement('div');hint.className='routeHint';hint.style.cssText='margin:8px 2px 3px;padding:10px 11px;border-radius:12px;background:#eef4ff;border:1px solid #d8e6ff;color:#3f526b;font-size:10px;line-height:1.4';hint.innerHTML='<b style="display:block;color:#173f76;margin-bottom:2px">Use this like a checklist</b>Tap a stop for details. Tap Go for navigation. The circle marks it complete. Each area shows what to cut first if time slips.';title.after(hint)}}
function runAudit(){auditImages();tightenFallbacks();enhanceAlerts();makeRouteUseful();syncFieldBar()}
function watch(){if(observer)return;observer=new MutationObserver(()=>{clearTimeout(window.__siteAudit);window.__siteAudit=setTimeout(runAudit,30)});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['src','class']});window.addEventListener('scroll',syncFieldBar,{passive:true});window.addEventListener('resize',syncFieldBar,{passive:true});document.addEventListener('click',()=>setTimeout(runAudit,60),true)}
function init(){ensureFieldBar();runAudit();watch();setTimeout(runAudit,600);setTimeout(runAudit,2200);setTimeout(runAudit,5000)}
document.addEventListener('DOMContentLoaded',init);
})();