(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let observer=null,fieldBar=null;
const wm=file=>'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent(file)+'?width=1600';
const corrections=[
 [/kobe|nunobiki|kitano|nankinmachi|meriken|harborland/i,wm('Kobe Nunobiki Herb Garden03n3200.jpg')],
 [/fushimi|inari/i,wm('Fushimi Inari Shrine @ Kyoto (13406174775).jpg')],
 [/shinjuku|kabukicho|golden gai|omoide|hanazono/i,wm('Shinjuku by Night.jpg')],
 [/asakusa|senso|skytree|akihabara|kappabashi|ueno|yanaka|ameyoko/i,wm('TokyoSkyTree.jpg')]
];
const forceFallback=/itoshima|futamigaura|keya no oto|shiraito falls|odaiba|ginza|tokyo station|marunouchi|yurakucho|teamlab|biovortex|planets|borderless/i;
function ensureFieldBar(){if(fieldBar)return fieldBar;fieldBar=document.createElement('div');fieldBar.className='fieldBar';fieldBar.id='fieldBar';fieldBar.innerHTML='<div class="fieldBarText"><small>CURRENT STOP</small><b>Loading…</b></div><a target="_blank" rel="noopener">Directions ↗</a>';document.body.appendChild(fieldBar);return fieldBar}
function currentVisible(){return $('#todayView')?.classList.contains('active')}
function syncFieldBar(){const bar=ensureFieldBar(),card=$('.focusCard'),name=$('.focusBody h2')?.textContent?.trim(),go=$('.focusBody .go');if(!currentVisible()||!card||!name||!go){bar.classList.remove('show');return}bar.querySelector('b').textContent=name;bar.querySelector('a').href=go.href;const r=card.getBoundingClientRect();bar.classList.toggle('show',r.bottom<120||r.top>window.innerHeight)}
function markBad(img){const shell=img?.closest('.visual');if(!shell)return;img.classList.remove('loaded');img.classList.add('failed');img.style.display='none';shell.classList.add('failed');shell.classList.remove('image-ok');const fb=$('.visual-fallback',shell);if(fb){fb.setAttribute('role','img');fb.setAttribute('aria-label',img.alt?`Photo unavailable. ${img.alt}`:'Photo unavailable')}}
function repairPhotoSource(img){if(!img||img.dataset.photoChecked==='1')return;img.dataset.photoChecked='1';const alt=(img.alt||'').trim();if(forceFallback.test(alt)){markBad(img);img.dataset.audited='1';return}for(const [re,url] of corrections){if(re.test(alt)&&img.src!==url){img.dataset.audited='0';img.style.display='';img.src=url;break}}}
function imageState(img){if(!img||img.dataset.audited==='1')return;img.dataset.audited='1';const shell=img.closest('.visual');const good=()=>{if(!shell)return;img.style.display='';img.classList.add('loaded');img.classList.remove('failed');shell.classList.add('image-ok');shell.classList.remove('failed')};const bad=()=>markBad(img);if(img.complete){img.naturalWidth>20?good():bad()}else{img.addEventListener('load',good,{once:true});img.addEventListener('error',bad,{once:true});setTimeout(()=>{if(!img.classList.contains('loaded')&&(!img.complete||img.naturalWidth<20))bad()},4500)}}
function auditImages(){$$('.visual-img').forEach(img=>{repairPhotoSource(img);imageState(img)})}
function tightenFallbacks(){$$('.visual.failed').forEach(v=>{const fb=$('.visual-fallback',v);if(fb&&!fb.querySelector('.fallback-note')){const n=document.createElement('small');n.className='fallback-note';n.textContent='Route information and navigation are still available';n.style.cssText='margin-top:7px;font-size:8px;opacity:.72;font-weight:800;letter-spacing:.02em';fb.appendChild(n)}})}
function enhanceAlerts(){$$('.alertsBox').forEach(x=>{if(!x.dataset.audited){x.dataset.audited='1';x.open=false}})}
function makeRouteUseful(){const page=$('#routeView .routePage');if(!page||page.dataset.audited)return;page.dataset.audited='1';const title=$('.pageTitle',page);if(title){const hint=document.createElement('div');hint.className='routeHint';hint.style.cssText='margin:8px 2px 4px;padding:10px 11px;border-radius:12px;background:#eef4ff;border:1px solid #d8e6ff;color:#3f526b;font-size:10px;line-height:1.4';hint.innerHTML='<b style="display:block;color:#173f76;margin-bottom:2px">Use this like a checklist</b><span>Tap a stop for details · Go opens navigation · ○ marks it done · each area tells you what to cut first.</span>';title.after(hint)}}
function normalizeLabels(){$$('.livePill').forEach(x=>x.textContent='YOU ARE HERE');$$('.sectionHead span').forEach(x=>{if(x.textContent==='COMING UP')x.textContent='NEXT'})}
function jstDate(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return''}}
function autoCurrentDay(){const T=window.JAPAN_TRIP;if(!T?.days?.length)return;const date=jstDate(),ix=T.days.findIndex(d=>d.date===date);if(ix<0)return;const key='japan-v4-auto-day';if(localStorage.getItem(key)===date)return;const chip=$(`.daychip[data-i="${ix}"]`);if(chip){localStorage.setItem(key,date);chip.click();setTimeout(()=>{const jump=$('#jumpTime');if(jump)jump.click()},50)}}
function runAudit(){auditImages();tightenFallbacks();enhanceAlerts();makeRouteUseful();normalizeLabels();syncFieldBar()}
function watch(){if(observer)return;observer=new MutationObserver(()=>{clearTimeout(window.__siteAudit);window.__siteAudit=setTimeout(runAudit,35)});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['src','class']});window.addEventListener('scroll',syncFieldBar,{passive:true});window.addEventListener('resize',syncFieldBar,{passive:true});document.addEventListener('click',()=>setTimeout(runAudit,70),true)}
function init(){ensureFieldBar();runAudit();autoCurrentDay();watch();setTimeout(runAudit,500);setTimeout(runAudit,1800);setTimeout(runAudit,5000)}
document.addEventListener('DOMContentLoaded',init);
})();