(()=>{
'use strict';
const T=window.JAPAN_TRIP,E=window.JAPAN_ENRICH||{placeInfo:{},typeTips:{}};if(!T)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DONE='japan-tool80-done',PREF='japan-tool80-pref',PHOTOS='japan-tool80-photos';
const state={day:0,view:'today',stop:0,overlay:null};let map=null;
const HERO={
'2026-09-22':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nagasaki%20City%20view%20from%20Mt%20Inasa04s.jpg?width=1800',
'2026-09-23':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sakurai%20Futamigaura.jpg?width=1800',
'2026-09-24':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kusasenri01.jpg?width=1800',
'2026-09-25':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Manai%20Falls%20at%20Takachiho%20Gorge.jpg?width=1800',
'2026-09-26':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Himeji%20castle%20in%20may%202015.jpg?width=1800',
'2026-09-27':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bamboo%20Grove%2C%20Arashiyama%2C%20Kyoto%2C%20Japan.jpg?width=1800',
'2026-09-28':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kiyomizu-dera%2C%20Kyoto%2C%20November%202016%20-01.jpg?width=1800',
'2026-09-29':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Fushimi%20Inari%20Shrine%20%40%20Kyoto%20%2813406174775%29.jpg?width=1800',
'2026-09-30':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rainbow%20Bridge%2C%20Odaiba%2C%20Tokyo.jpg?width=1800',
'2026-10-01':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kegon%20Falls%2C%20Nikko%20National%20Park%2C%20Japan.jpg?width=1800',
'2026-10-02':'https://commons.wikimedia.org/wiki/Special:Redirect/file/JP-kamakura-daibutsu-2.jpg?width=1800',
'2026-10-03':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Shibuya%20Crossing.jpg?width=1800',
'2026-10-04':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Asakusa%20Sensoji.jpg?width=1800',
'2026-10-05':'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tokyo-STA%20Marunouchi-Entrance%202023.jpg?width=1800'};
const EXCLUDE_PHOTO=new Set(['MOVE','TRAIN','DRIVE','LOGISTICS','HOME','BUFFER','ARRIVAL']);
const OFFICIAL=[
['JR Kyushu','https://www.jrkyushu.co.jp/english/'],['Itoshima / Fukuoka tourism','https://www.crossroadfukuoka.jp/en/'],['Takachiho Tourism','https://takachiho-kanko.info/'],['JMA Aso status','https://www.data.jma.go.jp/vois/data/report/activity_info/503.html'],['Aso crater access','https://www.aso-volcano.jp/'],['Himeji Castle','https://www.himejicastle.jp/en/'],['teamLab','https://www.teamlab.art/'],['Tobu Nikko','https://www.tobu.co.jp/en/'],['Shibuya Sky','https://www.shibuya-scramble-square.com/sky/'],['Tokyo Skytree','https://www.tokyo-skytree.jp/en/']];
const BOOKINGS=[
['Sep 23','Rental car + friend pickup','Itoshima first, back to Fukuoka Airport before the friend pickup, then Yufuin.'],
['Sep 29 · 09:00','teamLab Biovortex Kyoto','BOOKED. Leave main bags at the Kyoto Airbnb, collect them after.'],
['Sep 30 · 10:00','teamLab Planets','BOOKED. Protect the arrival buffer.'],
['Oct 1 · early','Tobu limited express to Nikko','Reserve the early practical train.'],
['Oct 2 · ~16:30','teamLab Borderless','Target this slot; Oct 2 current official hours extend to 22:00.'],
['Oct 3 · ~16:15','Shibuya Sky','Target daylight → sunset → blue hour.'],
['Oct 4 · ~16:15','Tokyo Skytree','Target daylight → sunset → night.']];
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function d(){return T.days[state.day]}function lodge(day=d()){return day.sleep&&T.lodgings?.[day.sleep]||null}
function stopObj(a,zi,si,gi,z){return{time:a[0],name:a[1],type:a[2],priority:a[3],query:a[4],lat:a[5],lng:a[6],wiki:a[7],desc:a[8],zi,si,gi,zone:z.name,zoneSummary:z.summary,zoneCut:z.cut}}
function stops(day=d()){let gi=0;return day.zones.flatMap((z,zi)=>z.stops.map((a,si)=>stopObj(a,zi,si,gi++,z)))}
function dest(s){return Number.isFinite(+s.lat)&&Number.isFinite(+s.lng)?`${+s.lat},${+s.lng}`:(s.query||s.name)}
function maps(q){return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function mode(s){return/DRIVE|ARRIVAL|LOGISTICS/.test(s.type)?'driving':/TRAIN|MOVE/.test(s.type)?'transit':'walking'}
function directions(s){return`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(dest(s))}&travelmode=${mode(s)}`}
function routeUrl(z){const ss=z.stops.map((a,i)=>stopObj(a,0,i,i,z));if(!ss.length)return'#';if(ss.length===1)return maps(dest(ss[0]));const first=ss[0],last=ss.at(-1),mid=ss.slice(1,-1).slice(0,8),tm=ss.some(s=>/DRIVE|LOGISTICS|ARRIVAL/.test(s.type))?'driving':ss.some(s=>/TRAIN|MOVE/.test(s.type))?'transit':'walking';return`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(dest(first))}&destination=${encodeURIComponent(dest(last))}${mid.length?`&waypoints=${encodeURIComponent(mid.map(dest).join('|'))}`:''}&travelmode=${tm}`}
function doneMap(){try{return JSON.parse(localStorage.getItem(DONE)||'{}')}catch{return{}}}
function sid(s,day=d()){return`${day.date}|${s.zi}|${s.si}`}function isDone(s,day=d()){return!!doneMap()[sid(s,day)]}
function setDone(s,v,day=d()){const m=doneMap();m[sid(s,day)]=v;localStorage.setItem(DONE,JSON.stringify(m))}
function progress(day=d()){const ss=stops(day),n=ss.filter(s=>isDone(s,day)).length;return{n,total:ss.length,pct:ss.length?Math.round(n*100/ss.length):0}}
function pri(p=''){const x=p.toLowerCase();return x==='must'||x==='book'?'must':x==='high'?'high':x==='flex'||x==='optional'?'flex':''}
function hero(day=d()){return HERO[day.date]||HERO['2026-10-05']}
function todayIndex(){try{const x=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),i=T.days.findIndex(y=>y.date===x);return i>=0?i:0}catch{return 0}}
function savePref(){localStorage.setItem(PREF,JSON.stringify({day:state.day,view:state.view,stop:state.stop}))}
function snapshot(){return{app:'japan-tool',day:state.day,view:state.view,stop:state.stop,overlay:state.overlay,scrollY:window.scrollY}}
function hash(){return`#${state.view}/${d().date}/${state.stop}`}
function load(){let p={};try{p=JSON.parse(localStorage.getItem(PREF)||'{}')}catch{}state.day=Number.isInteger(p.day)?Math.max(0,Math.min(T.days.length-1,p.day)):todayIndex();state.view=['today','map','trip','more','live'].includes(p.view)?p.view:'today';state.stop=Math.max(0,+p.stop||0);state.overlay=null;history.replaceState(snapshot(),'',hash())}
function nav(next={},scrollTop=true){const y=window.scrollY;history.replaceState({...snapshot(),scrollY:y},'',location.href);Object.assign(state,next);state.day=Math.max(0,Math.min(T.days.length-1,state.day));state.stop=Math.max(0,Math.min(Math.max(0,stops().length-1),state.stop));savePref();history.pushState({...snapshot(),scrollY:scrollTop?0:y},'',hash());renderAll();requestAnimationFrame(()=>window.scrollTo(0,scrollTop?0:y))}
function replace(next={},keep=true){const y=window.scrollY;Object.assign(state,next);savePref();history.replaceState({...snapshot(),scrollY:y},'',hash());renderAll();requestAnimationFrame(()=>window.scrollTo(0,keep?y:0))}
function renderRail(){const r=$('#dayRail');r.innerHTML=T.days.map((x,i)=>`<button class="daychip ${i===state.day?'active':''}" data-i="${i}"><b>${esc(x.label)}</b><span>${esc(x.city.split('→')[0].trim())}</span></button>`).join('');$$('.daychip',r).forEach(b=>b.onclick=()=>nav({day:+b.dataset.i,view:'today',stop:0,overlay:null},true));setTimeout(()=>$('.daychip.active',r)?.scrollIntoView({block:'nearest',inline:'center'}),10)}
function renderAlerts(day){if(!day.alerts?.length)return'';return`<div class="alerts">${day.alerts.map(a=>`<article class="alert ${a.k==='warning'?'warning':''}"><b>${esc(a.t)}</b><p>${esc(a.x)}</p></article>`).join('')}</div>`}
function stopRow(s){return`<button class="stoprow ${pri(s.priority)} ${isDone(s)?'done':''}" data-stop="${s.gi}"><span class="stime">${esc(s.time)}</span><span class="stoptext"><b>${esc(s.name)}</b><span>${esc(s.priority)} · ${esc(s.type)}</span></span><span class="chev">›</span></button>`}
function renderArea(z,zi,offset,day){const arr=z.stops.map((a,si)=>stopObj(a,zi,si,offset+si,z));return`<details class="area" ${zi===0?'open':''}><summary><div><small>AREA ${zi+1} · ${esc(z.time)}</small><h3>${esc(z.name)}</h3><p>${esc(z.summary)}</p></div><div class="areaCount">${arr.length}<br>stops</div></summary><div class="areaBody"><div class="areaRoute"><a href="${routeUrl(z)}" target="_blank" rel="noopener">Open route ↗</a><button data-start="${offset}">Start here</button></div><div class="timeline">${arr.map(stopRow).join('')}</div>${z.food?.length?`<div class="foodline">${z.food.map(f=>`<a href="${maps(f[1]||f[0])}" target="_blank"><b>${esc(f[0])}</b><span>${esc(f[2]||'')}</span></a>`).join('')}</div>`:''}${z.cut?`<div class="cut"><b>If behind:</b> ${esc(z.cut)}</div>`:''}</div></details>`}
function renderToday(){const day=d(),p=progress(day);let off=0;$('#todayView').innerHTML=`<section class="hero" style="background-image:url('${hero(day)}')"><div class="heroCopy"><div class="kicker">DAY ${state.day+1} · ${esc(day.label)}</div><h1>${esc(day.city)}</h1><p>${esc(day.mission)}</p><div class="heroActions"><button id="startDay">Start day</button><button class="secondary" id="heroMap">Map route</button></div></div></section><div class="wrap"><section class="summary"><div class="summaryTop"><div><b>${progress(day).total} stops · ${day.zones.length} areas</b><small>${esc(lodge(day)?.name||'Departure day')}</small></div><div class="pct">${p.pct}%</div></div><div class="track"><i style="width:${p.pct}%"></i></div><div class="summaryBtns"><button id="briefBtn">Day brief</button><button id="routeBtn">Full map</button><button id="sleepBtn">Sleep</button></div></section>${renderAlerts(day)}<div class="sectionTitle"><div><small>FULL DAY FLOW</small><h2>Route</h2></div><span>Tap any stop</span></div>${day.zones.map((z,zi)=>{const h=renderArea(z,zi,off,day);off+=z.stops.length;return h}).join('')}</div>`;
$('#startDay').onclick=()=>nav({view:'live',stop:state.stop||0,overlay:null},true);$('#heroMap').onclick=$('#routeBtn').onclick=()=>nav({view:'map',overlay:null},true);$('#briefBtn').onclick=()=>openOverlay({type:'brief'});$('#sleepBtn').onclick=()=>{const l=lodge();if(l)window.open(maps(l.address),'_blank')};$$('[data-stop]','#todayView').forEach(b=>b.onclick=()=>openOverlay({type:'stop',index:+b.dataset.stop}));$$('[data-start]','#todayView').forEach(b=>b.onclick=()=>nav({view:'live',stop:+b.dataset.start,overlay:null},true))}
function renderMap(){const day=d();$('#mapView').innerHTML=`<div class="mapPage"><section class="mapCard"><div class="mapHeader"><small>${esc(day.label)} · ROUTE MAP</small><h1>${esc(day.city)}</h1><p>Numbered pins show visit order. The line is sequence only; use the area links for actual road/transit directions.</p></div><div id="leafletMap" class="mapBox"></div><div class="mapRoutes">${day.zones.map(z=>`<a href="${routeUrl(z)}" target="_blank">${esc(z.name)} ↗</a>`).join('')}</div></section></div>`;if(state.view==='map')requestAnimationFrame(initMap)}
function initMap(){if(map){map.remove();map=null}const el=$('#leafletMap');if(!el)return;if(!window.L){el.innerHTML='<div style="padding:24px;font-size:11px;color:#777">Interactive map could not load. Use the route links below.</div>';return}const pts=stops().filter(s=>Number.isFinite(+s.lat)&&Number.isFinite(+s.lng));if(!pts.length)return;map=L.map(el,{zoomControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const ll=[];pts.forEach((s,i)=>{const p=[+s.lat,+s.lng];ll.push(p);const icon=L.divIcon({className:'',html:`<div class="pinIcon">${s.gi+1}</div>`,iconSize:[28,28],iconAnchor:[14,14]});const m=L.marker(p,{icon}).addTo(map);m.bindTooltip(`${s.time} · ${s.name}`,{direction:'top'});m.on('click',()=>openOverlay({type:'stop',index:s.gi}))});L.polyline(ll,{color:'#111',weight:3,opacity:.45,dashArray:'5,7'}).addTo(map);map.fitBounds(L.latLngBounds(ll),{padding:[28,28]})}
function renderTrip(){$('#tripView').innerHTML=`<div class="tripPage"><div class="pageHead"><h1>Japan</h1><p>One tool for the full Sep 22 → Oct 5 trip. Tap a day to open its route.</p></div><div class="daycards">${T.days.map((x,i)=>{const p=progress(x);return`<button class="daycard" data-day="${i}"><span class="dayphoto" style="background-image:url('${hero(x)}')"></span><span class="daycopy"><small>${esc(x.label)} · ${p.n}/${p.total} done</small><b>${esc(x.city)}</b><span>${esc(x.mission)}</span></span></button>`}).join('')}</div></div>`;$$('[data-day]','#tripView').forEach(b=>b.onclick=()=>nav({day:+b.dataset.day,view:'today',stop:0,overlay:null},true))}
function renderMore(){const lodges=Object.values(T.lodgings||{});$('#moreView').innerHTML=`<div class="morePage"><div class="pageHead"><h1>Trip essentials</h1><p>Only the things you actually need when logistics matter.</p></div><section class="moreGroup"><h2>Bookings & hard gates</h2>${BOOKINGS.map(x=>`<div class="moreItem"><b>${esc(x[0])} · ${esc(x[1])}</b><p>${esc(x[2])}</p></div>`).join('')}</section><section class="moreGroup"><h2>Sleep</h2>${lodges.map(x=>`<div class="moreItem"><b>${esc(x.name)}</b><p>${esc(x.address)}</p><a href="${maps(x.address)}" target="_blank">Open map ↗</a></div>`).join('')}</section><section class="moreGroup"><h2>Field rules</h2><div class="moreItem"><b>Kyushu driving</b><p>Drive left. Every driver needs the proper license/IDP/passport setup. Use ETC, return full, and assume mountain roads take longer than app estimates. Stop only at legal pullouts.</p></div><div class="moreItem"><b>Luggage</b><p>Road-trip Kyushu with small bags if possible. On Sep 29 leave main luggage at the Kyoto Airbnb during teamLab, then collect once before Kyoto Station.</p></div><div class="moreItem"><b>Cut system</b><p>Cut shopping, long meals, repeated viewpoints and optional interiors first. Never cut bookings, the primary anchor, safe transport buffers or the sleep destination.</p></div><div class="moreItem"><b>Emergency</b><p>Police 110 · ambulance/fire 119. For a rental-car accident: stop safely, handle injuries, call police even for a minor collision, then the rental company.</p></div></section><section class="moreGroup"><h2>Live checks</h2>${OFFICIAL.map(x=>`<div class="moreItem"><b>${esc(x[0])}</b><a href="${x[1]}" target="_blank" rel="noopener">Official site ↗</a></div>`).join('')}</section></div>`}
function renderLive(){const day=d(),ss=stops(),s=ss[Math.min(state.stop,ss.length-1)],next=ss[state.stop+1],p=progress(day);if(!s)return;$('#liveView').innerHTML=`<div class="livePage"><div class="liveTop"><button id="liveBack">‹ Back to route</button><span>${esc(day.label)} · ${p.pct}% done</span></div><article class="liveCard"><div class="livePhoto noPhoto" id="livePhoto"></div><div class="liveBody"><div class="liveMeta"><span>${esc(s.time)} · ${esc(s.priority)}</span><span>${state.stop+1}/${ss.length}</span></div><h1>${esc(s.name)}</h1><p>${esc(s.desc)}</p><div class="liveActions"><a href="${directions(s)}" target="_blank">GO NOW ↗</a><button id="doneNext">${isDone(s)?'Next':'Done + next'}</button></div><div class="liveStep"><button id="prevStop" ${state.stop===0?'disabled':''}>← Previous</button><button id="detailStop">Details</button><button id="nextStop" ${state.stop>=ss.length-1?'disabled':''}>Next →</button></div></div></article>${next?`<div class="nextUp"><small>UP NEXT · ${esc(next.time)}</small><b>${esc(next.name)}</b><p>${esc(next.desc)}</p></div>`:''}</div>`;loadExactPhoto($('#livePhoto'),s);$('#liveBack').onclick=()=>nav({view:'today',overlay:null},false);$('#prevStop').onclick=()=>replace({stop:Math.max(0,state.stop-1)},false);$('#nextStop').onclick=()=>replace({stop:Math.min(ss.length-1,state.stop+1)},false);$('#detailStop').onclick=()=>openOverlay({type:'stop',index:state.stop});$('#doneNext').onclick=()=>{if(!isDone(s))setDone(s,true);state.stop=Math.min(ss.length-1,state.stop+1);savePref();renderAll();toast('Updated')};}
function renderBrief(){const day=d(),l=lodge(),foods=day.zones.flatMap(z=>z.food||[]),cuts=day.zones.map(z=>z.cut).filter(Boolean);return`<div class="sheetBody"><div class="sheetMeta">${esc(day.label)} · DAY BRIEF</div><h2>${esc(day.city)}</h2><p>${esc(day.mission)}</p><div class="intel"><div class="intelRow"><b>Protect</b><p>${esc(day.zones.map(z=>z.stops.filter(s=>/MUST|BOOK/.test(s[3])).map(s=>s[1]).slice(0,3).join(', ')).filter(Boolean).join(' · '))}</p></div><div class="intelRow"><b>If late</b><p>${esc(cuts.join(' '))}</p></div><div class="intelRow"><b>Food</b><p>${esc(foods.length?foods.map(f=>f[0]).join(' · '):'Use fast on-route food; do not let meals control the clock.')}</p></div><div class="intelRow"><b>Sleep</b><p>${esc(l?`${l.name} · ${l.address}`:'Departure day')}</p></div><div class="intelRow"><b>Rule</b><p>Protect bookings, daylight anchors and safe transport. Cut optional interiors, shopping, queues and repeated viewpoints first.</p></div></div>${l?`<div class="sheetButtons"><a href="${maps(l.address)}" target="_blank">Sleep map ↗</a><button id="briefMap">Day map</button></div>`:''}</div>`}
function detailInfo(s){const x=E.placeInfo?.[s.name]||{},tip=E.typeTips?.[s.type]||'Protect the next hard deadline and do not overstay.';return{see:x.see||s.desc,photo:x.photo||photoTip(s),practical:x.practical||tip}}
function photoTip(s){if(/SHRINE|TEMPLE/.test(s.type))return'Get the approach, gate/torii and one wider context frame. Respect worship and photo restrictions.';if(/VIEW|PHOTO|SUNSET|NIGHT/.test(s.type))return'Get the signature wide view first, then one tighter detail or human-scale frame.';if(/NATURE|COAST/.test(s.type))return'Use leading lines and scale. Keep footing and barriers more important than the shot.';if(/NEIGHBORHOOD|STREET/.test(s.type))return'Look for layers, signs, people and a strong foreground instead of only wide streets.';return'Get the signature composition quickly, then experience the stop.'}
function renderStopSheet(index){const ss=stops(),s=ss[index];if(!s)return'';const info=detailInfo(s),next=ss[index+1],prev=ss[index-1];return`<div class="sheetPhoto ${EXCLUDE_PHOTO.has(s.type)?'noExact':'loading'}" id="detailPhoto" data-label="${esc(s.name)}"></div><div class="sheetBody"><div class="sheetMeta">${esc(s.time)} · ${esc(s.priority)} · ${esc(s.type)}</div><h2>${esc(s.name)}</h2><p>${esc(s.desc)}</p><div class="sheetButtons"><a href="${directions(s)}" target="_blank">Navigate ↗</a><button id="toggleDone">${isDone(s)?'Undo done':'Mark done'}</button></div><div class="intel"><div class="intelRow"><b>Do / see</b><p>${esc(info.see)}</p></div><div class="intelRow"><b>Photo</b><p>${esc(info.photo)}</p></div><div class="intelRow"><b>Practical</b><p>${esc(info.practical)}</p></div><div class="intelRow"><b>Flow</b><p>${esc(s.zoneSummary)}</p></div>${s.zoneCut?`<div class="intelRow"><b>If behind</b><p>${esc(s.zoneCut)}</p></div>`:''}${next?`<div class="intelRow"><b>Next</b><p>${esc(next.time)} · ${esc(next.name)} — ${esc(next.desc)}</p></div>`:''}</div><div class="sheetNav"><button id="sheetPrev" ${prev?'':'disabled'}>← Previous</button><button id="sheetNext" ${next?'':'disabled'}>Next →</button></div></div>`}
function openOverlay(o){nav({overlay:o},false)}function closeOverlay(){if(state.overlay)history.back();else hideSheet()}
function renderOverlay(){if(!state.overlay){hideSheet();return}$('#scrim').classList.add('open');$('#sheet').classList.add('open');$('#sheet').setAttribute('aria-hidden','false');if(state.overlay.type==='brief'){$('#sheetBody').innerHTML=renderBrief();$('#briefMap')&&($('#briefMap').onclick=()=>{state.overlay=null;nav({view:'map'},true)});return}const i=state.overlay.index,$body=$('#sheetBody');$body.innerHTML=renderStopSheet(i);const s=stops()[i];if(s&&!EXCLUDE_PHOTO.has(s.type))loadExactPhoto($('#detailPhoto'),s);$('#toggleDone').onclick=()=>{setDone(s,!isDone(s));renderOverlay();renderToday();toast(isDone(s)?'Marked done':'Marked incomplete')};$('#sheetPrev').onclick=()=>{if(i>0)replace({overlay:{type:'stop',index:i-1}},true)};$('#sheetNext').onclick=()=>{if(i<stops().length-1)replace({overlay:{type:'stop',index:i+1}},true)}}
function hideSheet(){$('#scrim').classList.remove('open');$('#sheet').classList.remove('open');$('#sheet').setAttribute('aria-hidden','true')}
function photoCache(){try{return JSON.parse(localStorage.getItem(PHOTOS)||'{}')}catch{return{}}}function cachePhoto(k,u){const c=photoCache();c[k]=u;const ks=Object.keys(c);if(ks.length>120)delete c[ks[0]];localStorage.setItem(PHOTOS,JSON.stringify(c))}
async function exactPhoto(s){if(EXCLUDE_PHOTO.has(s.type))return null;const key=(s.wiki||s.query||s.name).toLowerCase(),c=photoCache();if(c[key])return c[key];try{if(s.wiki){const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(s.wiki.replace(/ /g,'_'))}`);if(r.ok){const j=await r.json(),u=j.originalimage?.source||j.thumbnail?.source;if(u){cachePhoto(key,u);return u}}}}catch{}try{const q=`${s.name.replace(/·/g,' ')} Japan`,u=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrsearch=${encodeURIComponent(q)}&gsrlimit=1&prop=imageinfo&iiprop=url&iiurlwidth=1500&format=json&origin=*`,r=await fetch(u);if(r.ok){const j=await r.json(),pg=j.query?.pages&&Object.values(j.query.pages)[0],img=pg?.imageinfo?.[0]?.thumburl||pg?.imageinfo?.[0]?.url;if(img){cachePhoto(key,img);return img}}}catch{}return null}
async function loadExactPhoto(el,s){if(!el)return;if(EXCLUDE_PHOTO.has(s.type)){el.classList.add('noExact');el.classList.remove('loading','noPhoto');el.dataset.label=s.type;return}const u=await exactPhoto(s);if(!document.body.contains(el))return;if(!u){el.classList.add('noExact');el.classList.remove('loading','noPhoto');el.dataset.label=s.name;return}const img=new Image();img.onload=()=>{if(!document.body.contains(el))return;el.style.backgroundImage=`url("${u.replace(/"/g,'%22')}")`;el.classList.remove('loading','noPhoto','noExact')};img.onerror=()=>{el.classList.add('noExact');el.classList.remove('loading','noPhoto');el.dataset.label=s.name};img.src=u}
function renderSearch(q=''){const box=$('#searchResults'),term=q.trim().toLowerCase();if(!term){box.innerHTML='<div class="searchHint">Search any shrine, temple, viewpoint, neighborhood, booking or route stop.</div>';return}const hits=[];T.days.forEach((day,di)=>stops(day).forEach(s=>{const hay=[day.label,day.city,s.name,s.type,s.zone,s.desc].join(' ').toLowerCase();if(hay.includes(term))hits.push({day,di,s})}));box.innerHTML=hits.slice(0,100).map(h=>`<button class="searchResult" data-di="${h.di}" data-si="${h.s.gi}"><small>${esc(h.day.label)} · ${esc(h.s.time)}</small><b>${esc(h.s.name)}</b><span>${esc(h.s.zone)}</span></button>`).join('')||'<div class="searchHint">No matching stop.</div>';$$('.searchResult',box).forEach(b=>b.onclick=()=>{$('#searchLayer').classList.remove('open');nav({day:+b.dataset.di,view:'today',stop:+b.dataset.si,overlay:{type:'stop',index:+b.dataset.si}},true)})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1400)}
function renderAll(){renderRail();renderToday();renderMap();renderTrip();renderMore();renderLive();$$('.view').forEach(v=>v.classList.toggle('active',v.id===state.view+'View'));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#tabbar').classList.toggle('hidden',state.view==='live');$('#backBtn').classList.toggle('on',!!state.overlay||state.view==='live'||state.view!=='today');renderOverlay()}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>nav({view:b.dataset.view,overlay:null},true));$('#brandBtn').onclick=()=>nav({view:'trip',overlay:null},true);$('#searchBtn').onclick=()=>{$('#searchLayer').classList.add('open');$('#searchInput').value='';renderSearch('');setTimeout(()=>$('#searchInput').focus(),30)};$('#searchInput').oninput=e=>renderSearch(e.target.value);$('#searchClose').onclick=()=>$('#searchLayer').classList.remove('open');$('#sheetClose').onclick=closeOverlay;$('#sheetBack').onclick=closeOverlay;$('#scrim').onclick=closeOverlay;$('#backBtn').onclick=()=>{if(state.overlay)return closeOverlay();if(state.view==='live')return nav({view:'today'},false);if(state.view!=='today')return nav({view:'today'},true)};window.addEventListener('popstate',e=>{const s=e.state;if(!s||s.app!=='japan-tool')return;state.day=s.day??0;state.view=s.view||'today';state.stop=s.stop??0;state.overlay=s.overlay||null;savePref();renderAll();requestAnimationFrame(()=>window.scrollTo(0,Number.isFinite(s.scrollY)?s.scrollY:0))});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(state.overlay)closeOverlay();else $('#searchLayer').classList.remove('open')}})}
load();bind();renderAll();
})();